/**
 * Smoke-tests for lib/curriculum-stats.ts (auto-generated by
 * scripts/build-curriculum-stats.mjs, run as part of `prepare`).
 *
 * If this file doesn't exist the whole import below throws at module
 * resolution time — that's the regression: tsc fails with TS2307 on
 * lib/store.ts and components/home/HomeApp.tsx (both import from it).
 *
 * The `prepare` script now generates it on every `npm install` so fresh
 * clones no longer need a manual `npm run build:curriculum-stats` step.
 */
import { describe, it, expect } from 'vitest';
import {
  SECTIONS,
  SECTION_TOTAL_COURSES,
  SECTION_COURSE_IDS,
  MODULE_META,
  MODULE_COURSE_IDS,
  getSectionByIdFast,
} from '@/lib/curriculum-stats';
import { TOTAL_COURSES } from '@/lib/curriculum';

describe('curriculum-stats — generated artifact contract', () => {
  it('SECTIONS contains all 12 expected section IDs', () => {
    const ids = SECTIONS.map((s) => s.id);
    const expected = [
      'fundamentals', 'biomedical', 'clinical', 'allied', 'skills',
      'hss', 'threads', 'frontier', 'business', 'regulatory', 'career', 'tech',
    ];
    expect(ids).toEqual(expected);
  });

  it('getSectionByIdFast returns correct section', () => {
    const sec = getSectionByIdFast('biomedical');
    expect(sec).toBeDefined();
    expect(sec?.id).toBe('biomedical');
  });

  it('getSectionByIdFast returns undefined for unknown id', () => {
    expect(getSectionByIdFast('nonexistent' as never)).toBeUndefined();
  });

  it('SECTION_TOTAL_COURSES sums to TOTAL_COURSES from curriculum.ts', () => {
    const statsTotal = Object.values(SECTION_TOTAL_COURSES).reduce((s, n) => s + n, 0);
    expect(statsTotal).toBe(TOTAL_COURSES);
  });

  it('SECTION_COURSE_IDS lengths match SECTION_TOTAL_COURSES', () => {
    for (const [sectionId, count] of Object.entries(SECTION_TOTAL_COURSES)) {
      const ids = SECTION_COURSE_IDS[sectionId as keyof typeof SECTION_COURSE_IDS];
      expect(ids).toBeDefined();
      expect(ids.length).toBe(count);
    }
  });

  it('MODULE_META contains at least one entry with title and color', () => {
    const entries = Object.entries(MODULE_META);
    expect(entries.length).toBeGreaterThan(0);
    const [, meta] = entries[0]!;
    expect(meta).toHaveProperty('title');
    expect(meta).toHaveProperty('color');
  });

  it('MODULE_COURSE_IDS maps module numbers to non-empty course arrays', () => {
    const entries = Object.entries(MODULE_COURSE_IDS);
    expect(entries.length).toBeGreaterThan(0);
    for (const [, courseIds] of entries) {
      expect(Array.isArray(courseIds)).toBe(true);
      expect((courseIds as string[]).length).toBeGreaterThan(0);
    }
  });

  it('MODULE_COURSE_IDS course IDs are present in SECTION_COURSE_IDS', () => {
    const allIds = new Set(
      Object.values(SECTION_COURSE_IDS).flat(),
    );
    for (const [, courseIds] of Object.entries(MODULE_COURSE_IDS)) {
      for (const id of courseIds as string[]) {
        expect(allIds.has(id)).toBe(true);
      }
    }
  });
});
