/**
 * P0-CR-2 auto-generated smoke test for runner 'neo-low-flow-o2'.
 *
 * Проверяет, что runner экспортирует валидный default + has expected
 * shape (kind, inputs). НЕ проверяет clinical correctness — для этого
 * пишите hand-test в tests/calculators/neo-low-flow-o2.test.ts (если будет, то
 * этот auto-test ИГНОРИРУЕТСЯ генератором).
 *
 * Generated by scripts/gen-smoke-tests.mjs. Не редактируй вручную —
 * regenerate'ится при следующем запуске.
 */
import { describe, it, expect } from 'vitest';
import runner from '@/lib/runners/neo-low-flow-o2';

describe('runner:neo-low-flow-o2 smoke', () => {
  it('exports default', () => {
    expect(runner).toBeDefined();
    expect(runner).not.toBeNull();
  });

  it('has valid kind', () => {
    expect((runner as { kind?: string }).kind).toMatch(/^(score|calculator)$/);
  });

  it('has inputs array', () => {
    const r = runner as { inputs?: unknown[] };
    expect(Array.isArray(r.inputs)).toBe(true);
  });

  it('has reference string (если калькулятор)', () => {
    const r = runner as { kind?: string; reference?: string };
    if (r.kind === 'calculator' || r.kind === 'score') {
      // reference опционален в типе но рекомендуем для citation
      if (r.reference !== undefined) {
        expect(typeof r.reference).toBe('string');
      }
    }
  });
});
