/**
 * P0-CR-2 auto-generated smoke test for runner 'ralph'.
 *
 * Проверяет, что runner экспортирует валидный default + has expected
 * shape (kind, inputs) AND что compute() не падает на дефолтных входах
 * и возвращает {value} (для калькуляторов и score-runners с custom
 * compute). НЕ проверяет clinical correctness — для этого пишите
 * hand-test в tests/calculators/ralph.test.ts (если будет, то этот
 * auto-test ИГНОРИРУЕТСЯ генератором).
 *
 * Generated by scripts/gen-smoke-tests.mjs. Не редактируй вручную —
 * regenerate'ится при следующем запуске.
 */
import { describe, it, expect } from 'vitest';
import runner from '@/lib/runners/ralph';
import { buildSmokeDefaults } from '@/tests/helpers/smoke-defaults';

describe('runner:ralph smoke', () => {
  it('exports default', () => {
    expect(runner).toBeDefined();
    expect(runner).not.toBeNull();
  });

  it('has valid kind', () => {
    expect((runner as { kind?: string }).kind).toMatch(/^(score|calculator)$/);
  });

  it('has inputs array', () => {
    const r = runner as { inputs?: unknown[] };
    expect(Array.isArray(r.inputs)).toBe(true);
  });

  it('has reference string (если калькулятор)', () => {
    const r = runner as { kind?: string; reference?: string };
    if (r.kind === 'calculator' || r.kind === 'score') {
      // reference опционален в типе но рекомендуем для citation
      if (r.reference !== undefined) {
        expect(typeof r.reference).toBe('string');
      }
    }
  });

  it('compute() runs on default inputs and returns a defined value', () => {
    // Behavioural smoke: builds a default input map (preset[0] if present,
    // else per-input sensible defaults) and calls compute(). Only runs when
    // a compute fn exists — pure band-based scores have none.
    const r = runner as {
      kind?: string;
      inputs?: unknown[];
      presets?: { values?: Record<string, unknown> }[];
      compute?: (v: Record<string, number | boolean | string>) => { value?: unknown };
    };
    if (typeof r.compute !== 'function') {
      // band-based score with no custom compute — nothing behavioural to smoke
      expect(r.kind).toBe('score');
      return;
    }
    const defaults = buildSmokeDefaults(r.inputs, r.presets);
    let result: { value?: unknown } | undefined;
    expect(() => { result = r.compute!(defaults); }).not.toThrow();
    expect(result).toBeDefined();
    expect(result).not.toBeNull();
    expect(result!.value).toBeDefined();
  });
});
