/**
 * AUTO-GENERATED from lib/runners/*.ts by scripts/build-tool-meta.mjs.
 * Do not edit by hand — rerun via `npm run build:tool-meta`.
 *
 * Exists so tool-meta.ts (and therefore ToolsPage) does not need to
 * import every runner module just to know which tools are
 * implemented and which countries they apply to.
 */

export const RUNNER_IDS: readonly string[] = [
  "4at",
  "4s-af",
  "4t-pph",
  "4t",
  "9-line",
  "aa-gradient",
  "aaa",
  "aast",
  "abc-tash",
  "abcd2",
  "abi",
  "abpm",
  "absi",
  "abw",
  "acc-aha-hf",
  "acdu",
  "acog-preeclampsia",
  "act",
  "adrogue-madias",
  "afs-enzian",
  "ahls",
  "ahs-ecc",
  "aims65",
  "aldrete",
  "alvarado-pas",
  "alvarado",
  "aminoglycoside",
  "anaphylaxis",
  "anion-gap",
  "antidote",
  "anzcor",
  "ao-ota",
  "ao-spine",
  "apache",
  "apfel",
  "apgar",
  "asa-e",
  "asa-ps",
  "asccp",
  "ascvd",
  "asia",
  "aspects",
  "asrs",
  "atlanta",
  "atls",
  "ats",
  "audit-c",
  "avpu",
  "ballard",
  "barthel",
  "basdai",
  "bdi",
  "beck-ssi",
  "berlin-ards",
  "bethesda-cyto",
  "big",
  "bis",
  "bisap",
  "bishop",
  "bls-acls",
  "bmi",
  "bode",
  "bodyfat",
  "boey",
  "bova",
  "bp-guidelines",
  "bpi",
  "bps-icu",
  "braden",
  "bromage",
  "broselow",
  "brugada",
  "bsa-dose",
  "bsa-dubois",
  "bsa-haycock",
  "bsa-mosteller",
  "c-ssrs",
  "ca-corrected",
  "cage-audit",
  "cage",
  "calvert",
  "cam-icu",
  "cam",
  "can-cspine",
  "can-ct-head",
  "caprini",
  "ccs",
  "cdai",
  "cdc-acip",
  "cdc-growth",
  "cdr",
  "ceap",
  "centor",
  "cfs",
  "chads-vasc",
  "charlson",
  "child-meld",
  "ciwa",
  "ckd-epi",
  "clavien",
  "cmqcc",
  "cockcroft",
  "code-stemi",
  "conners",
  "cows",
  "cpot",
  "cpp",
  "crafft",
  "crawford",
  "crib",
  "ctas",
  "ctcae-neuro",
  "ctg",
  "curb65",
  "cystatin",
  "das28",
  "dast",
  "denis",
  "denver",
  "diamond-forrester",
  "dka",
  "dn4",
  "doac",
  "door-to",
  "downes",
  "dragon",
  "drip-rate",
  "drs",
  "dubowitz",
  "duke-treadmill",
  "duke",
  "eat26",
  "eceb",
  "ecog",
  "edacs",
  "edmonton-frail",
  "edss",
  "ehra",
  "ems-assess",
  "engel",
  "epals",
  "epds",
  "epi-who",
  "epworth",
  "erc",
  "esc-nste",
  "esc-pe",
  "esi",
  "etc",
  "euroscore",
  "evans",
  "fagerstrom",
  "far-ru",
  "fast-us",
  "fast",
  "fena",
  "feverpain",
  "fib4",
  "figo-staging",
  "finnegan",
  "flacc",
  "forrest",
  "forrester",
  "four",
  "fps-r",
  "framingham-hf",
  "framingham",
  "frax-men",
  "friedewald",
  "frykman",
  "fst",
  "gad7",
  "garden",
  "gbs",
  "gcs",
  "gds",
  "geneva",
  "glim",
  "gold",
  "grace",
  "greene",
  "gustilo",
  "gwtg",
  "h2fpef",
  "hachinski",
  "hacor",
  "ham-a",
  "ham-d",
  "harris-hip",
  "has-bled",
  "hawkins",
  "hba1c",
  "hbb",
  "head-growth",
  "heart",
  "hellp",
  "henderson",
  "hics",
  "hinchey",
  "hoehn",
  "holliday-segar",
  "homa-ir",
  "house-brackmann",
  "htn-tod",
  "hughes-gbs",
  "hunt-hess",
  "iadpsg",
  "ibw-devine",
  "ibw-robinson",
  "ich",
  "ichd3",
  "ikdc",
  "ilae",
  "ilcor",
  "imci",
  "impact",
  "improve-bleed",
  "insall-salvati",
  "insulin-correction",
  "intergrowth",
  "iota",
  "ipss",
  "iss",
  "iv-dilution",
  "katz-adl",
  "kellgren",
  "khorana",
  "kigali",
  "killip",
  "kocher",
  "kps",
  "kramer",
  "kts",
  "lbw",
  "lille",
  "lqts",
  "lund-malmo",
  "lund-rosner",
  "mace2",
  "maddrey",
  "maggic",
  "mallampati",
  "march-paws",
  "marshall-ct",
  "mason-mayo",
  "mayo-uc",
  "mcdonald",
  "mcgill",
  "mchat-autism",
  "mchat",
  "mchs-russia",
  "mdrd",
  "mehta",
  "meld",
  "meows",
  "mews",
  "mg-kg",
  "mgfa",
  "midas",
  "mini-cog",
  "mmpi",
  "mmrc",
  "mmse",
  "mna",
  "moca",
  "modified-brooke",
  "mods-lods",
  "morse",
  "mpi",
  "mpm",
  "mrs-stroke",
  "mrs",
  "msfc",
  "mtp",
  "mts",
  "murray-ecmo",
  "murray",
  "must",
  "na-corrected",
  "naegele",
  "neer",
  "news2",
  "nihss",
  "nips",
  "niss",
  "npi",
  "npsi",
  "nrp",
  "nrs2002",
  "nsqip",
  "nt-probnp",
  "nutric",
  "nyha",
  "ohca",
  "osm-gap",
  "ottawa-ankle",
  "outerbridge",
  "padua",
  "painad",
  "palm-coein",
  "pals",
  "panss",
  "parkland-brooke",
  "parkland",
  "pas",
  "pasi",
  "pat",
  "pcl5",
  "pdq39",
  "pears",
  "pecarn-chalice",
  "pecarn-cspine",
  "pecarn-head",
  "perc",
  "pesi",
  "pews",
  "pf-ratio",
  "pgcs",
  "phq9",
  "phtls-nm",
  "phtls",
  "pierce",
  "pipkin",
  "plasma-osm",
  "plr",
  "poisindex",
  "popq",
  "possum",
  "pram",
  "preserve",
  "prevent",
  "psqi",
  "pts",
  "qrisk3",
  "qsofa",
  "qtc",
  "rancho",
  "ranson",
  "rap-prx",
  "raschke",
  "rass",
  "rcog-37a",
  "rcog-vte",
  "rcri",
  "red-blood",
  "resp",
  "reynolds",
  "rifle",
  "rochester",
  "rockall",
  "rockwood",
  "rotterdam",
  "rox",
  "rsbi",
  "rts",
  "ru-growth",
  "ru-military",
  "ru-skoraya",
  "ru-vaccine",
  "rule-9",
  "rule-nines",
  "russe",
  "rutherford",
  "salter-harris",
  "sanders",
  "saps",
  "scat",
  "schatzker",
  "schwab",
  "schwartz",
  "score2-ru",
  "score2",
  "sepsis3",
  "sflt",
  "sga",
  "sgarbossa",
  "shock-index",
  "sieve-sort",
  "silverman",
  "simpson",
  "sipa",
  "sirs",
  "slic",
  "slums",
  "snoop",
  "sofa",
  "spetzler",
  "spin",
  "stan",
  "stanag",
  "stanford",
  "start-civ",
  "start",
  "stess",
  "stop-bang",
  "straw10",
  "strongkids",
  "svv",
  "tal",
  "tanner",
  "tccc-17",
  "tccc",
  "tcns",
  "tecc-17",
  "tecc",
  "thompson",
  "timi",
  "tinetti",
  "tisdale",
  "toast",
  "tokyo",
  "tonnis",
  "trali",
  "triss",
  "tscherne",
  "ucla-shoulder",
  "uk-green",
  "uk-who",
  "unit-bili",
  "unit-chol",
  "unit-creatinine",
  "unit-glucose",
  "unit-hb",
  "updrs",
  "us-dates",
  "vanco-auc",
  "vanderbilt",
  "vas",
  "villalta",
  "warfarin",
  "water-deficit",
  "weber",
  "wells-dvt",
  "wells-pe",
  "westley",
  "wfns",
  "who-dehydr",
  "who-growth",
  "who-ish",
  "who-mec",
  "whr",
  "wilkins",
  "wilson-arne",
  "winter",
  "wong-baker",
  "years",
  "ymrs",
  "young-burgess",
];

export const RUNNER_COUNTRIES: Readonly<Record<string, string>> = {
  "4at": "США",
  "4s-af": "Международный (ESC 2020)",
  "4t-pph": "Международный",
  "4t": "Международный (ASH 2018)",
  "9-line": "NATO / US DoD / WHO / IHI",
  "aaa": "Международный (SVS · ESVS · USPSTF)",
  "aast": "Международный (AAST, США)",
  "abi": "Международный (AHA · ESC · SVS)",
  "abpm": "Международный (ESC/ESH · ACC/AHA · NICE · РКО)",
  "absi": "Международный (ABA, ISBI)",
  "abw": "Международный",
  "acc-aha-hf": "США · ЕС · РФ",
  "acdu": "США · Международный",
  "acog-preeclampsia": "Международный (ACOG, ISSHP, РОАГ)",
  "adrogue-madias": "Международный",
  "afs-enzian": "Международный (ASRM, ESHRE, #Enzian)",
  "ahls": "США (AACT/Univ Arizona), международные сертификаты AHLS",
  "ahs-ecc": "AHA (США), ERC (Европа), IAED/MPDS (60+ стран), SAMU (Франция)",
  "alvarado-pas": "Международный",
  "aminoglycoside": "США · Международный",
  "anaphylaxis": "WAO / EAACI / NIAID - международно",
  "antidote": "Международные референсы (USA, ЕС)",
  "anzcor": "Австралия, Новая Зеландия",
  "ao-ota": "Международный (AO Foundation + Orthopaedic Trauma Association)",
  "ao-spine": "Международный",
  "apache": "Международный (оригинал США)",
  "apgar": "Международный",
  "asa-e": "Международный",
  "asccp": "США (ASCCP); адаптация ESGO/IFCPC",
  "ascvd": "США (ACC/AHA)",
  "asia": "Международный (ASIA / ISCoS)",
  "asrs": "Международный (WHO)",
  "atlanta": "Международный (IAP/APA, ACG guidelines)",
  "atls": "ACS-COT (США), 86 стран (курсы ATLS проводятся официально)",
  "ats": "Австралия",
  "avpu": "Международный (ATLS / APLS / NEWS2)",
  "ballard": "Международный",
  "barthel": "Международный",
  "bdi": "Международный",
  "beck-ssi": "Международный",
  "berlin-ards": "Международный (ESICM/ATS/SCCM)",
  "bethesda-cyto": "Международный (Bethesda)",
  "big": "Международный (derived US military + civilian)",
  "bis": "Международный (ERC/ESICM)",
  "bls-acls": "AHA (США, Канада, международно)",
  "bmi": "Международный (ВОЗ)",
  "bodyfat": "США (U.S. Navy) · Международный",
  "boey": "Международный (WSES guidelines 2020)",
  "bova": "Международный",
  "bp-guidelines": "США (ACC/AHA) · ЕС (ESC/ESH) · Великобритания (NICE) · РФ (РКО)",
  "bpi": "Международный (MD Anderson)",
  "bps-icu": "Международный (SCCM PADIS 2018)",
  "braden": "Международный (NPUAP / EPUAP / PPPIA)",
  "broselow": "Международный (AHA/PALS)",
  "brugada": "Международный (ESC · AHA · HRS)",
  "bsa-dose": "США · ЕС · Международный",
  "bsa-dubois": "Международный",
  "bsa-haycock": "Международный (особ. педиатрия и онкология)",
  "bsa-mosteller": "США · Международный",
  "c-ssrs": "США · ЕС · РФ · FDA стандарт",
  "cage-audit": "Международный (ВОЗ)",
  "calvert": "Международный (ASCO, ESMO)",
  "cam-icu": "Международный (SCCM PADIS 2018)",
  "cam": "США",
  "can-cspine": "Международный",
  "can-ct-head": "Канада · Международный",
  "caprini": "Международный (ACCP 2012, AAOS, ASCO)",
  "ccs": "Международный (CCS · ESC · ACC/AHA)",
  "cdai": "Международный (ECCO 2020, ACG 2018, STRIDE-II 2021)",
  "cdc-acip": "США",
  "cdc-growth": "США · международный 2-20 лет",
  "ceap": "Международный (AVF · ESVS · SVS)",
  "cfs": "Международный (NICE, ESICM)",
  "chads-vasc": "Международный (ESC, AHA, РКО)",
  "ciwa": "Международный",
  "ckd-epi": "Международный (KDIGO)",
  "cmqcc": "США (CMQCC/AWHONN), UK (RCOG 52), международно",
  "cockcroft": "США (FDA) · ЕС (EMA) · Международный",
  "code-stemi": "США (AHA/ACC), ЕС (ESC), РФ",
  "conners": "США / Международный",
  "cows": "Международный",
  "cpot": "Международный (SCCM PADIS 2018)",
  "cpp": "Международный",
  "crafft": "США (AAP, NIAAA)",
  "crawford": "Международный (ESVS · SVS · ESC 2024)",
  "crib": "Международный (NICU)",
  "ctas": "Канада",
  "ctcae-neuro": "Международный (NCI / FDA / EMA)",
  "ctg": "Международный (FIGO, ACOG, NICHD)",
  "cystatin": "Международный (KDIGO)",
  "dast": "Международный",
  "denis": "Международный",
  "denver": "США · международный",
  "diamond-forrester": "ЕС · Международный",
  "dka": "Великобритания (JBDS) · США (ADA) · Международный (ISPAD)",
  "dn4": "Международный (IASP NeuPSIG)",
  "doac": "Международный (EHRA / ESC) · США (FDA) · ЕС (EMA)",
  "door-to": "США (AHA/ACC), ЕС, международно",
  "downes": "Международный",
  "dragon": "Международный (Helsinki Stroke)",
  "drip-rate": "Международный",
  "dubowitz": "Международный (исторический)",
  "duke-treadmill": "США · международный",
  "duke": "Международный (ISCVID · ESC 2023 · AHA)",
  "eat26": "Международный",
  "eceb": "AAP / ВОЗ / USAID - global low-resource settings",
  "ecog": "Международный (ECOG/WHO)",
  "edacs": "Австралия · Н.Зеландия · международная",
  "edmonton-frail": "Канада · Международный",
  "ehra": "Международный (ESC / EHRA)",
  "ems-assess": "NAEMT / NREMT (США), стандарт EMS обучения международно",
  "epals": "Европа (ERC), Великобритания (APLS), международно",
  "epi-who": "Международный · Германия · Франция",
  "epworth": "Международный",
  "erc": "Европа (ERC member councils)",
  "esc-nste": "ЕС · международный",
  "esc-pe": "ЕС · международный",
  "esi": "США",
  "etc": "ERC / ESTES (Европа, ≥ 30 стран)",
  "euroscore": "ЕС · международный",
  "evans": "Международный",
  "far-ru": "Россия (ФАР)",
  "fast-us": "Международный (ATLS)",
  "fast": "Международный (AHA/ASA, ESO)",
  "feverpain": "Великобритания (NICE)",
  "fib4": "Международный (AASLD 2023, EASL 2021, WHO)",
  "figo-staging": "Международный (FIGO)",
  "finnegan": "Международный",
  "flacc": "Международный",
  "four": "Международный (Mayo Clinic / AAN)",
  "fps-r": "Международный (IASP)",
  "framingham-hf": "Международный",
  "framingham": "США · Международный",
  "frax-men": "Международный (FRAX, NOF, AACE)",
  "frykman": "Международный (исторический)",
  "fst": "Международный",
  "garden": "Международный",
  "gcs": "Международный",
  "gds": "Международный · рекомендовано у ≥65 лет",
  "geneva": "Международный (ESC 2019)",
  "glim": "Международный (ESPEN · ASPEN · FELANPE · PENSA)",
  "grace": "Международный (ESC, AHA)",
  "greene": "Международный",
  "gustilo": "Международный",
  "gwtg": "США (AHA), применяется в 2600+ госпиталях",
  "h2fpef": "Международный",
  "hacor": "Международный",
  "ham-a": "Международный",
  "ham-d": "Международный",
  "harris-hip": "Международный (Oxford - UK NJR стандарт)",
  "hawkins": "Международный",
  "hbb": "АAP / ВОЗ / USAID - low-resource settings глобально",
  "head-growth": "Международный (ВОЗ)",
  "hellp": "Международный",
  "henderson": "Международный",
  "hics": "США (CalEMSA + FEMA), адаптирован в ЕС, РФ, Азии",
  "house-brackmann": "Международный",
  "htn-tod": "Международный (ESC/ESH · ACC/AHA · РКО)",
  "hughes-gbs": "Международный",
  "iadpsg": "Международный (IADPSG/WHO), США (C-C), UK (NICE), РФ (РОАГ)",
  "ibw-robinson": "Международный (США - клиническая практика)",
  "ikdc": "Международный",
  "ilcor": "Международный (AHA, ERC, ANZCOR, HSFC, RCSA, IAHF, InterAmerican HF)",
  "imci": "WHO / страны с ограниченными ресурсами",
  "impact": "Международный (IMPACT + CRASH консорциумы)",
  "improve-bleed": "Международный (ACCP 2012, ASH 2018)",
  "insall-salvati": "Международный",
  "insulin-correction": "США (ADA) · Международный (ISPAD)",
  "intergrowth": "Международный",
  "iota": "Международный (IOTA, ESGO)",
  "iss": "Международный",
  "iv-dilution": "Международный",
  "katz-adl": "Международный",
  "kellgren": "Международный",
  "khorana": "Международный (ASCO 2020, ESMO 2022, NCCN)",
  "kigali": "Низкоресурсные страны (валидировано в Руанде)",
  "kps": "Международный",
  "kramer": "Международный",
  "kts": "LMIC (Уганда, Кения, LMIC-адаптация)",
  "lbw": "Международный",
  "lqts": "Международный (HRS · ESC · AHA)",
  "lund-malmo": "Европа (Швеция, Скандинавия) · Международный",
  "lund-rosner": "Международный",
  "maggic": "Международный",
  "mallampati": "Международный",
  "march-paws": "Стандарт TCCC / NATO / US DoD",
  "marshall-ct": "Международный",
  "mason-mayo": "Международный",
  "mayo-uc": "Международный (ACG 2019, ECCO 2022)",
  "mcgill": "Международный (IMMPACT)",
  "mchat-autism": "Международный (AAP)",
  "mchat": "Международный",
  "mchs-russia": "Российская Федерация",
  "meld": "США (UNOS) · Международный",
  "meows": "Великобритания/Европа",
  "mews": "Великобритания/Европа",
  "mg-kg": "Международный",
  "mgfa": "Международный (MGFA)",
  "midas": "Международный",
  "mmpi": "США / Международный",
  "mna": "Международный · Гериатрия",
  "modified-brooke": "США (ABA / ABLS) · Международный",
  "mods-lods": "Международный",
  "morse": "Международный",
  "mpi": "Международный (Германия, Европа, РФ)",
  "mpm": "Международный",
  "msfc": "Международный",
  "mtp": "Международный",
  "mts": "Великобритания/Европа",
  "murray-ecmo": "Международный (ELSO)",
  "murray": "Международный",
  "must": "Великобритания · ЕС · Международный",
  "neer": "Международный",
  "news2": "Великобритания (NHS, RCP) · EU",
  "nips": "Международный",
  "niss": "Международный",
  "npsi": "Международный",
  "nrp": "AAP (США), международно адаптируется",
  "nrs2002": "Европа (ESPEN) · Международный",
  "nutric": "Международный · ОРИТ (ASPEN/SCCM)",
  "ohca": "Международный",
  "osm-gap": "Международный",
  "outerbridge": "Международный",
  "padua": "Международный (ACCP 2012, ASH 2018)",
  "painad": "Международный",
  "palm-coein": "Международный (FIGO, RCOG, NICE)",
  "pals": "Международный (AHA)",
  "panss": "Международный",
  "parkland-brooke": "Международный (ABA, ATLS, ABLS)",
  "parkland": "Международный (ATLS, ABA)",
  "pat": "Международный (AAP/AHA PALS)",
  "pcl5": "Международный (US VA)",
  "pears": "AHA (США, международно)",
  "pecarn-chalice": "США (PECARN) · Великобритания (CHALICE) · Канада (CATCH)",
  "pecarn-cspine": "Международный (PECARN)",
  "pecarn-head": "Международный (PECARN)",
  "pesi": "Международный (ESC 2019, AHA 2011)",
  "pews": "Международный",
  "pgcs": "Международный",
  "phtls-nm": "NAEMT (США), международно - 80+ стран",
  "phtls": "США, международный (NAEMT, ITLS International)",
  "pierce": "Международный",
  "pipkin": "Международный",
  "plr": "Международный",
  "poisindex": "США (Micromedex), международная референсная БД",
  "popq": "Международный (ICS, IUGA)",
  "pram": "Международный",
  "prevent": "США (AHA 2023)",
  "psqi": "Международный",
  "pts": "Международный (США ACS)",
  "qrisk3": "Великобритания (NICE CG181)",
  "qsofa": "Международный (SSC, Sepsis-3)",
  "rancho": "США · Международный (нейрореабилитация)",
  "ranson": "Международный",
  "rap-prx": "Международный (Cambridge)",
  "raschke": "США · Международный (ACCP 2012)",
  "rass": "Международный (SCCM PADIS 2018)",
  "rcog-37a": "Великобритания (RCOG); адаптация в ЕС",
  "rcog-vte": "UK (RCOG) · международно принята",
  "red-blood": "US DoD / NATO / постепенная civilian adoption",
  "resp": "Международный (ELSO)",
  "reynolds": "США",
  "rifle": "Международный (KDIGO)",
  "rochester": "США · Европа (с адаптациями)",
  "rockwood": "Международный",
  "rotterdam": "Международный (ESHRE/ASRM, AE-PCOS, Teede 2023)",
  "rox": "Международный",
  "rsbi": "Международный",
  "rts": "Международный",
  "ru-growth": "Российская Федерация · СНГ",
  "ru-military": "Российская Федерация (ВС РФ, МО РФ, ВМА им. Кирова)",
  "ru-skoraya": "Россия, СНГ (адаптация)",
  "ru-vaccine": "Российская Федерация",
  "rule-9": "Международный (ABA, EMSB, ERC)",
  "rule-nines": "Международный (ATLS, ABA)",
  "russe": "Международный",
  "rutherford": "Международный (SVS · ESVS · ACC/AHA)",
  "salter-harris": "Международный",
  "sanders": "Международный",
  "saps": "Международный (European standard)",
  "scat": "Международный (CISG / FIFA / IOC)",
  "schatzker": "Международный",
  "score2-ru": "РФ · СНГ (high-risk region)",
  "score2": "Европа (ESC)",
  "sepsis3": "Международный (SCCM/ESICM Task Force 2016, SSC 2021)",
  "sflt": "Международный (EMA одобрено)",
  "sga": "Международный · Хирургия · Нефрология · Онкология",
  "sgarbossa": "Международный",
  "sieve-sort": "Великобритания · NHS England",
  "silverman": "РФ · СНГ · Латинская Америка",
  "simpson": "Международный",
  "sipa": "Международный (США ATLS/PALS)",
  "sirs": "Международный (исторический)",
  "slic": "Международный (Spine Trauma Study Group)",
  "spetzler": "Международный",
  "spin": "Международный",
  "stan": "Европа (Neoventa STAN; Швеция, Нидерланды, UK)",
  "stanag": "NATO (альянс)",
  "stanford": "Международный (ESC 2024 · AHA/ACC · STS)",
  "start-civ": "США · Международный",
  "start": "Международный",
  "straw10": "Международный (STRAW+10)",
  "strongkids": "Нидерланды · ЕС · Международный (педиатрия)",
  "svv": "Международный",
  "tal": "Международный",
  "tanner": "Международный",
  "tccc-17": "DoD / JTS (США), NATO STANAG, международно (combat medic programs)",
  "tccc": "Стандарт NATO / US DoD / СНГ (адаптации)",
  "tcns": "Международный",
  "tecc-17": "C-TECC (США), международная адаптация EMS систем",
  "tecc": "США, Канада, EU, civilian EMS/SWAT",
  "thompson": "Международный",
  "tinetti": "Международный",
  "tisdale": "Международный (AHA · HRS · CredibleMeds)",
  "toast": "Международный (AHA/ASA, ESO)",
  "tokyo": "Международный (Tokyo Guidelines)",
  "tonnis": "Международный",
  "trali": "Международный (ISBT)",
  "triss": "Международный (MTOS)",
  "tscherne": "Европа (Германия, Австрия, Швейцария - стандарт)",
  "ucla-shoulder": "Международный",
  "uk-green": "Великобритания (NHS)",
  "uk-who": "Великобритания · Ирландия",
  "unit-bili": "Международный",
  "unit-chol": "Международный",
  "unit-creatinine": "Международный (США - mg/dL; СИ - мкмоль/л)",
  "unit-glucose": "Международный (США используют mg/dL; СИ - ммоль/л)",
  "unit-hb": "Международный",
  "us-dates": "Международный (ACOG, ISUOG)",
  "vanco-auc": "США (IDSA/ASHP) · Международный",
  "vanderbilt": "США · международный",
  "vas": "Международный (IASP · ВОЗ)",
  "villalta": "Международный (ISTH · ESVS)",
  "warfarin": "Международный (ACCP) · США · ЕС",
  "water-deficit": "Международный",
  "weber": "Международный",
  "who-dehydr": "Международный (ВОЗ / IMCI)",
  "who-growth": "Международный (ВОЗ)",
  "who-ish": "Всемирный (14 субрегионов WHO)",
  "who-mec": "Международный (WHO); США (CDC US MEC 2024)",
  "whr": "Международный (ВОЗ)",
  "wilkins": "Международный (ESC · AHA · ACC)",
  "wong-baker": "Международный",
  "years": "Международный (ESC 2019)",
  "ymrs": "Международный",
  "young-burgess": "Международный",
};
