/**
 * AUTO-GENERATED from lib/runners/*.ts by scripts/build-tool-meta.mjs.
 * Do not edit by hand — rerun via `npm run build:tool-meta`.
 *
 * Exists so tool-meta.ts (and therefore ToolsPage) does not need to
 * import every runner module just to know which tools are
 * implemented and which countries they apply to.
 */

export const RUNNER_IDS: readonly string[] = [
  "4at",
  "4s-af",
  "4t",
  "aa-gradient",
  "aaa",
  "abcd2",
  "abi",
  "abpm",
  "abw",
  "acc-aha-hf",
  "acdu",
  "act",
  "adrogue-madias",
  "aims65",
  "aldrete",
  "alvarado-pas",
  "alvarado",
  "aminoglycoside",
  "anion-gap",
  "apache",
  "apfel",
  "apgar",
  "asa-e",
  "asa-ps",
  "ascvd",
  "asia",
  "aspects",
  "ats",
  "audit-c",
  "avpu",
  "ballard",
  "barthel",
  "basdai",
  "bisap",
  "bishop",
  "bmi",
  "bode",
  "bodyfat",
  "bova",
  "bp-guidelines",
  "bpi",
  "braden",
  "bromage",
  "broselow",
  "brugada",
  "bsa-dose",
  "bsa-dubois",
  "bsa-haycock",
  "bsa-mosteller",
  "ca-corrected",
  "cage",
  "calvert",
  "cam",
  "can-ct-head",
  "caprini",
  "ccs",
  "cdc-acip",
  "cdc-growth",
  "cdr",
  "ceap",
  "centor",
  "cfs",
  "chads-vasc",
  "charlson",
  "child-meld",
  "ckd-epi",
  "clavien",
  "cockcroft",
  "cpot",
  "crawford",
  "crib",
  "ctas",
  "ctcae-neuro",
  "curb65",
  "cystatin",
  "das28",
  "denver",
  "diamond-forrester",
  "dka",
  "dn4",
  "doac",
  "downes",
  "dragon",
  "drip-rate",
  "drs",
  "dubowitz",
  "duke-treadmill",
  "duke",
  "ecog",
  "edacs",
  "edmonton-frail",
  "edss",
  "ehra",
  "engel",
  "epds",
  "epi-who",
  "epworth",
  "esc-nste",
  "esc-pe",
  "esi",
  "euroscore",
  "evans",
  "fagerstrom",
  "fast",
  "fena",
  "feverpain",
  "finnegan",
  "flacc",
  "forrest",
  "forrester",
  "four",
  "fps-r",
  "framingham-hf",
  "framingham",
  "friedewald",
  "gad7",
  "gbs",
  "gcs",
  "geneva",
  "glim",
  "gold",
  "grace",
  "h2fpef",
  "hachinski",
  "has-bled",
  "hba1c",
  "head-growth",
  "heart",
  "henderson",
  "hinchey",
  "hoehn",
  "holliday-segar",
  "homa-ir",
  "house-brackmann",
  "htn-tod",
  "hughes-gbs",
  "hunt-hess",
  "ibw-devine",
  "ibw-robinson",
  "ich",
  "ichd3",
  "ilae",
  "imci",
  "impact",
  "improve-bleed",
  "insulin-correction",
  "intergrowth",
  "ipss",
  "iv-dilution",
  "katz-adl",
  "khorana",
  "killip",
  "kocher",
  "kps",
  "kramer",
  "lbw",
  "lille",
  "lqts",
  "lund-malmo",
  "mace2",
  "maddrey",
  "maggic",
  "mallampati",
  "marshall-ct",
  "mcdonald",
  "mcgill",
  "mchat",
  "mdrd",
  "meld",
  "meows",
  "mews",
  "mg-kg",
  "mgfa",
  "midas",
  "mini-cog",
  "mmrc",
  "mmse",
  "mna",
  "moca",
  "modified-brooke",
  "mods-lods",
  "morse",
  "mpm",
  "mrs-stroke",
  "mrs",
  "msfc",
  "mts",
  "must",
  "na-corrected",
  "naegele",
  "news2",
  "nihss",
  "nips",
  "npi",
  "npsi",
  "nrs2002",
  "nsqip",
  "nt-probnp",
  "nutric",
  "nyha",
  "osm-gap",
  "ottawa-ankle",
  "padua",
  "painad",
  "pals",
  "parkland",
  "pas",
  "pasi",
  "pat",
  "pdq39",
  "pecarn-chalice",
  "pecarn-cspine",
  "pecarn-head",
  "perc",
  "pesi",
  "pews",
  "pf-ratio",
  "pgcs",
  "phq9",
  "plasma-osm",
  "possum",
  "pram",
  "prevent",
  "psqi",
  "pts",
  "qrisk3",
  "qsofa",
  "qtc",
  "rancho",
  "raschke",
  "rcog-vte",
  "rcri",
  "reynolds",
  "rochester",
  "rockall",
  "ru-growth",
  "ru-vaccine",
  "rule-nines",
  "rutherford",
  "saps",
  "scat",
  "schwab",
  "schwartz",
  "score2-ru",
  "score2",
  "sga",
  "sgarbossa",
  "shock-index",
  "silverman",
  "simpson",
  "sipa",
  "slic",
  "slums",
  "snoop",
  "sofa",
  "spetzler",
  "stanford",
  "start",
  "stess",
  "stop-bang",
  "strongkids",
  "tal",
  "tanner",
  "tcns",
  "thompson",
  "timi",
  "tinetti",
  "tisdale",
  "toast",
  "uk-green",
  "uk-who",
  "unit-bili",
  "unit-chol",
  "unit-creatinine",
  "unit-glucose",
  "unit-hb",
  "updrs",
  "vanco-auc",
  "vanderbilt",
  "vas",
  "villalta",
  "warfarin",
  "water-deficit",
  "wells-dvt",
  "wells-pe",
  "westley",
  "wfns",
  "who-dehydr",
  "who-growth",
  "who-ish",
  "whr",
  "wilkins",
  "wilson-arne",
  "winter",
  "wong-baker",
  "years",
];

export const RUNNER_COUNTRIES: Readonly<Record<string, string>> = {
  "4at": "США",
  "4s-af": "Международный (ESC 2020)",
  "4t": "Международный (ASH 2018)",
  "aaa": "Международный (SVS · ESVS · USPSTF)",
  "abi": "Международный (AHA · ESC · SVS)",
  "abpm": "Международный (ESC/ESH · ACC/AHA · NICE · РКО)",
  "abw": "Международный",
  "acc-aha-hf": "США · ЕС · РФ",
  "acdu": "США · Международный",
  "adrogue-madias": "Международный",
  "alvarado-pas": "Международный",
  "aminoglycoside": "США · Международный",
  "apache": "Международный (оригинал США)",
  "apgar": "Международный",
  "asa-e": "Международный",
  "ascvd": "США (ACC/AHA)",
  "asia": "Международный (ASIA / ISCoS)",
  "ats": "Австралия",
  "avpu": "Международный (ATLS / APLS / NEWS2)",
  "ballard": "Международный",
  "barthel": "Международный",
  "bmi": "Международный (ВОЗ)",
  "bodyfat": "США (U.S. Navy) · Международный",
  "bova": "Международный",
  "bp-guidelines": "США (ACC/AHA) · ЕС (ESC/ESH) · Великобритания (NICE) · РФ (РКО)",
  "bpi": "Международный (MD Anderson)",
  "braden": "Международный (NPUAP / EPUAP / PPPIA)",
  "broselow": "Международный (AHA/PALS)",
  "brugada": "Международный (ESC · AHA · HRS)",
  "bsa-dose": "США · ЕС · Международный",
  "bsa-dubois": "Международный",
  "bsa-haycock": "Международный (особ. педиатрия и онкология)",
  "bsa-mosteller": "США · Международный",
  "calvert": "Международный (ASCO, ESMO)",
  "cam": "США",
  "can-ct-head": "Канада · Международный",
  "caprini": "Международный (ACCP 2012, AAOS, ASCO)",
  "ccs": "Международный (CCS · ESC · ACC/AHA)",
  "cdc-acip": "США",
  "cdc-growth": "США · международный 2–20 лет",
  "ceap": "Международный (AVF · ESVS · SVS)",
  "cfs": "Международный (NICE, ESICM)",
  "chads-vasc": "Международный (ESC, AHA, РКО)",
  "ckd-epi": "Международный (KDIGO)",
  "cockcroft": "США (FDA) · ЕС (EMA) · Международный",
  "cpot": "Международный (SCCM PADIS 2018)",
  "crawford": "Международный (ESVS · SVS · ESC 2024)",
  "crib": "Международный (NICU)",
  "ctas": "Канада",
  "ctcae-neuro": "Международный (NCI / FDA / EMA)",
  "cystatin": "Международный (KDIGO)",
  "denver": "США · международный",
  "diamond-forrester": "ЕС · Международный",
  "dka": "Великобритания (JBDS) · США (ADA) · Международный (ISPAD)",
  "dn4": "Международный (IASP NeuPSIG)",
  "doac": "Международный (EHRA / ESC) · США (FDA) · ЕС (EMA)",
  "downes": "Международный",
  "dragon": "Международный (Helsinki Stroke)",
  "drip-rate": "Международный",
  "dubowitz": "Международный (исторический)",
  "duke-treadmill": "США · международный",
  "duke": "Международный (ISCVID · ESC 2023 · AHA)",
  "ecog": "Международный (ECOG/WHO)",
  "edacs": "Австралия · Н.Зеландия · международная",
  "edmonton-frail": "Канада · Международный",
  "ehra": "Международный (ESC / EHRA)",
  "epi-who": "Международный · Германия · Франция",
  "epworth": "Международный",
  "esc-nste": "ЕС · международный",
  "esc-pe": "ЕС · международный",
  "esi": "США",
  "euroscore": "ЕС · международный",
  "evans": "Международный",
  "fast": "Международный (AHA/ASA, ESO)",
  "feverpain": "Великобритания (NICE)",
  "finnegan": "Международный",
  "flacc": "Международный",
  "four": "Международный (Mayo Clinic / AAN)",
  "fps-r": "Международный (IASP)",
  "framingham-hf": "Международный",
  "framingham": "США · Международный",
  "gcs": "Международный",
  "geneva": "Международный (ESC 2019)",
  "glim": "Международный (ESPEN · ASPEN · FELANPE · PENSA)",
  "grace": "Международный (ESC, AHA)",
  "h2fpef": "Международный",
  "head-growth": "Международный (ВОЗ)",
  "henderson": "Международный",
  "house-brackmann": "Международный",
  "htn-tod": "Международный (ESC/ESH · ACC/AHA · РКО)",
  "hughes-gbs": "Международный",
  "ibw-robinson": "Международный (США — клиническая практика)",
  "imci": "WHO / страны с ограниченными ресурсами",
  "impact": "Международный (IMPACT + CRASH консорциумы)",
  "improve-bleed": "Международный (ACCP 2012, ASH 2018)",
  "insulin-correction": "США (ADA) · Международный (ISPAD)",
  "intergrowth": "Международный",
  "iv-dilution": "Международный",
  "katz-adl": "Международный",
  "khorana": "Международный (ASCO 2020, ESMO 2022, NCCN)",
  "kps": "Международный",
  "kramer": "Международный",
  "lbw": "Международный",
  "lqts": "Международный (HRS · ESC · AHA)",
  "lund-malmo": "Европа (Швеция, Скандинавия) · Международный",
  "maggic": "Международный",
  "mallampati": "Международный",
  "marshall-ct": "Международный",
  "mcgill": "Международный (IMMPACT)",
  "mchat": "Международный",
  "meld": "США (UNOS) · Международный",
  "meows": "Великобритания/Европа",
  "mews": "Великобритания/Европа",
  "mg-kg": "Международный",
  "mgfa": "Международный (MGFA)",
  "midas": "Международный",
  "mna": "Международный · Гериатрия",
  "modified-brooke": "США (ABA / ABLS) · Международный",
  "mods-lods": "Международный",
  "morse": "Международный",
  "mpm": "Международный",
  "msfc": "Международный",
  "mts": "Великобритания/Европа",
  "must": "Великобритания · ЕС · Международный",
  "news2": "Великобритания (NHS, RCP) · EU",
  "nips": "Международный",
  "npsi": "Международный",
  "nrs2002": "Европа (ESPEN) · Международный",
  "nutric": "Международный · ОРИТ (ASPEN/SCCM)",
  "osm-gap": "Международный",
  "padua": "Международный (ACCP 2012, ASH 2018)",
  "painad": "Международный",
  "pals": "Международный (AHA)",
  "parkland": "Международный (ATLS, ABA)",
  "pat": "Международный (AAP/AHA PALS)",
  "pecarn-chalice": "США (PECARN) · Великобритания (CHALICE) · Канада (CATCH)",
  "pecarn-cspine": "Международный (PECARN)",
  "pecarn-head": "Международный (PECARN)",
  "pesi": "Международный (ESC 2019, AHA 2011)",
  "pews": "Международный",
  "pgcs": "Международный",
  "pram": "Международный",
  "prevent": "США (AHA 2023)",
  "psqi": "Международный",
  "pts": "Международный (США ACS)",
  "qrisk3": "Великобритания (NICE CG181)",
  "qsofa": "Международный (SSC, Sepsis-3)",
  "rancho": "США · Международный (нейрореабилитация)",
  "raschke": "США · Международный (ACCP 2012)",
  "rcog-vte": "UK (RCOG) · международно принята",
  "reynolds": "США",
  "rochester": "США · Европа (с адаптациями)",
  "ru-growth": "Российская Федерация · СНГ",
  "ru-vaccine": "Российская Федерация",
  "rule-nines": "Международный (ATLS, ABA)",
  "rutherford": "Международный (SVS · ESVS · ACC/AHA)",
  "saps": "Международный (European standard)",
  "scat": "Международный (CISG / FIFA / IOC)",
  "score2-ru": "РФ · СНГ (high-risk region)",
  "score2": "Европа (ESC)",
  "sga": "Международный · Хирургия · Нефрология · Онкология",
  "sgarbossa": "Международный",
  "silverman": "РФ · СНГ · Латинская Америка",
  "simpson": "Международный",
  "sipa": "Международный (США ATLS/PALS)",
  "slic": "Международный (Spine Trauma Study Group)",
  "spetzler": "Международный",
  "stanford": "Международный (ESC 2024 · AHA/ACC · STS)",
  "start": "Международный",
  "strongkids": "Нидерланды · ЕС · Международный (педиатрия)",
  "tal": "Международный",
  "tanner": "Международный",
  "tcns": "Международный",
  "thompson": "Международный",
  "tinetti": "Международный",
  "tisdale": "Международный (AHA · HRS · CredibleMeds)",
  "toast": "Международный (AHA/ASA, ESO)",
  "uk-green": "Великобритания (NHS)",
  "uk-who": "Великобритания · Ирландия",
  "unit-bili": "Международный",
  "unit-chol": "Международный",
  "unit-creatinine": "Международный (США — mg/dL; СИ — мкмоль/л)",
  "unit-glucose": "Международный (США используют mg/dL; СИ — ммоль/л)",
  "unit-hb": "Международный",
  "vanco-auc": "США (IDSA/ASHP) · Международный",
  "vanderbilt": "США · международный",
  "vas": "Международный (IASP · ВОЗ)",
  "villalta": "Международный (ISTH · ESVS)",
  "warfarin": "Международный (ACCP) · США · ЕС",
  "water-deficit": "Международный",
  "who-dehydr": "Международный (ВОЗ / IMCI)",
  "who-growth": "Международный (ВОЗ)",
  "who-ish": "Всемирный (14 субрегионов WHO)",
  "whr": "Международный (ВОЗ)",
  "wilkins": "Международный (ESC · AHA · ACC)",
  "wong-baker": "Международный",
  "years": "Международный (ESC 2019)",
};
