"""+5 protocols (45 → 50)."""
import json, sys
from pathlib import Path
if sys.stdout.encoding != "utf-8": sys.stdout.reconfigure(encoding="utf-8")
ROOT = Path(__file__).parent.parent
JSON_PATH = ROOT / "public" / "neonatal-guidelines.json"


def g(id_, ru, en, cat, content, refs):
    return {"id": id_, "title_ru": ru, "title_en": en, "category": cat, "content": content, "references": refs}


NEW = [
    g("guide_lp_neonatal", "Lumbar puncture у новорождённого — техника",
      "Neonatal Lumbar Puncture — Technique",
      "neuro",
      "## Indications\n\n- Suspected meningitis (sepsis workup, especially LOS)\n- HSV ПЦР (CSF) при vesicles или encephalitis suspicion\n- Therapeutic CSF drainage при PHVD (post-haemorrhagic ventricular dilatation)\n- Diagnostic CSF analysis в IEM workup\n\n## Contraindications\n\n- Severe coagulopathy (platelets < 50, INR > 1.5)\n- Severe thrombocytopenia (< 30 — relative)\n- Hemodynamic instability\n- Skin infection at site\n- Severe anatomic abnormalities (myelomeningocele)\n- Increased ICP с herniation risk (rare у newborn — fontanelle compensates)\n\n## Preparation\n\n- Position: lateral knee-chest OR sitting (knee-to-chest)\n- Mark line between iliac crests = L4 spinous process\n- Site: L3-L4 OR L4-L5 interspace (avoid higher — spinal cord ends ~L3 у newborn)\n- Sucrose 0.5 мл oral 2 мин до procedure\n- Local anesthesia: lidocaine 1 % 0.1-0.3 мл infiltrate\n- Sterile drape + povidone-iodine OR chlorhexidine\n\n## Procedure\n\n1. **Stylet + needle:** 22G × 1.5 inch styletted spinal needle preferred (avoids epidermal cell carryover causing later epidermoid tumor)\n2. **Bevel up:** до dural puncture for cleaner pass\n3. **Slow advancement** through skin, subcutaneous tissue, ligaments\n4. **Pop** through ligamentum flavum + dura\n5. **Remove stylet:** check для CSF flow\n6. **Collect** 0.5-1 мл per tube × 4 tubes (CSF cell count, glucose, protein, culture, ПЦР HSV)\n7. **Replace stylet** before withdrawing needle (prevents tissue track)\n8. **Apply pressure** × 30 sec, then sterile dressing\n\n## CSF normal values neonatal\n\n| Parameter | Term | Preterm |\n|---|---|---|\n| **WBC** | < 20 /µл | < 30 /µл |\n| **% PMN** | < 60 % | < 60 % |\n| **Glucose** | 2.2-4.4 ммоль/л (40-80 mg/dL) — > 60 % serum | Same |\n| **Protein** | 0.4-1.2 г/л | 0.6-1.5 г/л |\n| **RBC** | < 700 /µл (traumatic up to 1000) | Same |\n\n## Traumatic tap correction\n\n- WBC corrected = WBC observed − (1 × WBC peripheral × RBC observed / RBC peripheral)\n- Or simpler: subtract 1 WBC per 700 RBC\n\n## Send for\n\n- **Cell count + differential** (Tube 1 OR 4)\n- **Glucose + protein** (Tube 2)\n- **Culture + Gram stain** (Tube 3)\n- **ПЦР HSV** (если suspected — Tube 4 or extra)\n- **Cytology / cytogenetics** если needed\n\n## Complications\n\n- Traumatic tap (RBC > 1000 → falsely elevated WBC)\n- Post-LP headache (rare у newborn)\n- Epidermoid tumor (very rare — prevented by stylet use)\n- Spinal hematoma (very rare у newborn)\n- Bloody tap\n\n## Calculator Bordik\n- neo-perinatal-infections-class\n- neo-acyclovir-dose (HSV)\n\n## Источники\n- AAP COFN — Procedures 2024\n- Polin RA. Pediatrics 2012;129:1006",
      ["AAP COFN Procedures 2024", "Polin RA. Pediatrics 2012;129:1006"]),

    g("guide_thrombosis_neonatal_management", "Тромбоз у новорождённого — алгоритм",
      "Neonatal Thrombosis — Management Algorithm",
      "metabolic",
      "## Categories\n\n### Catheter-related (most common)\n- UVC, UAC, PICC, CVC associated\n- 1-3 % с indwelling catheters\n- Often asymptomatic — detected on routine echo / Doppler\n\n### Renal vein thrombosis\n- ELBW, polycythemia, dehydration, IDM\n- Hematuria, palpable abdominal mass, thrombocytopenia\n\n### Cerebral sinovenous thrombosis (CSVT)\n- Dehydration, infection, polycythemia\n- Seizures, lethargy, focal deficits\n\n### Arterial thromboembolism\n- Aortic (UAC-related)\n- Iliofemoral (catheter complication)\n- Cerebral (perinatal stroke)\n\n## Workup\n\n- **Doppler ultrasound** — first-line vessels\n- **Echo** — intracardiac, IVC tip\n- **MRV** — cerebral, renal\n- **Coagulation panel + thrombophilia screen** (FII G20210A, FV Leiden, ATIII, Protein C/S, anticardiolipin)\n- **Imaging affected organ** (kidney, brain)\n\n## Treatment decisions\n\n### Asymptomatic catheter-related — Conservative\n- Remove catheter ASAP\n- Serial Doppler monitoring\n- Most resolve spontaneously\n\n### Symptomatic / occlusive / large — Anticoagulation\n- **Heparin** continuous IV: 28 ед/кг/h, titrate aPTT 60-85 sec OR anti-Xa 0.3-0.7\n- **LMWH (enoxaparin):** 1-1.5 мг/кг q12h SC, titrate anti-Xa 0.5-1.0\n- **Duration:** 6 нед — 3 мес typically\n- **Bleeding precautions:** monitor для GI bleed, ICH (especially IVH risk)\n\n### Life/limb-threatening — Thrombolysis\n- **Alteplase (rt-PA)** 0.1-0.5 мг/кг/h IV × 6 ч\n- **Limb / organ ischemia** specifically\n- **High bleeding risk** у newborn — last-resort\n- ICU + interventional radiology consult\n\n### Catheter clearance (occluded line)\n- Alteplase 0.5-2 мг intra-luminal × 30-120 мин dwell\n- Attempt aspirate\n- Repeat × 1 if needed\n\n## Avoid у newborn\n\n- **Aspirin** — Reye syndrome risk\n- **Routine anticoagulation** для asymptomatic small thrombi\n- **Warfarin** — narrow therapeutic window, slow onset, vit K interaction\n\n## Calculator Bordik\n- neo-heparin (continuous infusion)\n- neo-enoxaparin\n- neo-alteplase-cvc-dose (intra-luminal)\n- neo-recombinant-factor-vii\n\n## Источники\n- Monagle P et al. Chest 2012;141:e737S — ACCP Pediatric\n- Saracco P et al. Acta Paediatr 2009;98:1252",
      ["Monagle P et al. Chest 2012;141:e737S", "Saracco P et al. Acta Paediatr 2009;98:1252"]),

    g("guide_meconium_management", "Аспирация мекония — management",
      "Meconium Aspiration Management",
      "respiratory",
      "## Risk factors\n\n- **MSAF** (meconium-stained amniotic fluid) — 10-15 % всех родов\n- **Post-term** (≥ 41 нед)\n- **IUGR / SGA**\n- **Maternal hypertension / preeclampsia**\n- **Fetal distress** intrapartum\n\n## NRP 8 ed. (2021) approach\n\n### Vigorous infant (good cry/tone, HR > 100)\n- **NO routine tracheal suctioning**\n- Routine resuscitation: dry, stimulate, position, warm\n- Skin-to-skin if stable\n\n### Non-vigorous infant (apnea/poor tone/HR < 100)\n- **Standard PPV first** (изменено с 2015 NRP 7 ed. — больше not routine intubation)\n- **If PPV not effective** (no chest rise) → **intubate + tracheal suction** через мекониум-aspirator\n- Затем continue PPV / resuscitation\n\n## MAS spectrum severity\n\n### Mild (FiO₂ < 40 %)\n- Symptomatic с tachypnea, retractions\n- O₂ via NC/CPAP\n- Self-limiting обычно 3-5 d\n\n### Moderate (FiO₂ 40-60 %, MV indication)\n- Volume-targeted MV preferred\n- Permissive hypercapnia (PaCO₂ 50-60 если pH > 7.25)\n- Sedation + analgesia\n- Empiric ABX (ампициллин + гентамицин) — pneumonia не excluded\n\n### Severe (OI > 15-25)\n- **Surfactant** 100-200 мг/кг intratracheal q6h × 2-4 doses (Cochrane 2014, Wiswell 2002)\n- **HFOV** при air leak ИЛИ persistent hypoxemia\n- **iNO** 20 ppm если PPHN (OI > 25)\n- **ECMO** rescue OI > 40\n\n## Common complications\n\n- **PPHN** (~30 % severe MAS) — see PPHN protocol\n- **Pneumothorax** / pneumomediastinum (10-30 %)\n- **Pneumonia** (secondary)\n- **BPD** (если survived MV > 28 d)\n- **Long-term:** asthma-like wheeze, RAD\n\n## Calculator Bordik\n- neo-resus-doses\n- neo-resp-indices\n- neo-surfactant-dose\n- neo-ino-dose\n\n## Источники\n- Aziz K et al. Pediatrics 2021;147:e2020038505E — NRP 8 ed.\n- Wiswell TE et al. Pediatrics 2002;109:1081 — surfactant\n- Vain NE et al. Lancet 2004;364:597",
      ["Aziz K et al. Pediatrics 2021;147:e2020038505E", "Wiswell TE et al. Pediatrics 2002;109:1081"]),

    g("guide_anaphylaxis_neonatal", "Anaphylaxis у новорождённого",
      "Neonatal Anaphylaxis",
      "metabolic",
      "## Triggers (rare у newborn — но possible)\n\n- **Drugs:** vaccines, IVIG, antibiotics (β-lactams, vancomycin, surfactant rare), IV contrast, latex\n- **Food** (rare у newborn before solid feeds)\n- **Insect stings** (rare)\n\n## Recognition\n\n### Skin (90 %)\n- Urticaria, flushing\n- Angioedema (lips, eyelids)\n\n### Respiratory (75 %)\n- Stridor (laryngeal edema)\n- Wheezing, bronchospasm\n- Apnea, severe distress\n\n### Cardiovascular (50 %)\n- Hypotension, shock\n- Tachycardia (then bradycardia terminal)\n- Pallor, mottling\n\n### GI (40 %)\n- Vomiting, diarrhea\n\n## Acute management\n\n### Step 1: Epinephrine (FIRST-line, IM preferred)\n- **0.01 мг/кг IM** anterolateral thigh (vastus lateralis)\n- Use 1 мг/мл concentration (not 1:10000)\n- Repeat q5-15 мин prn\n- **NOT IV initially** (cardiac arrhythmia risk)\n- IV continuous infusion 0.05-1 мкг/кг/мин если refractory shock\n\n### Step 2: Position + airway\n- Supine (or trendelenburg if hypotension)\n- Suction if airway obstruction\n- Bag-mask ventilation OR intubation if severe\n- 100 % O₂\n\n### Step 3: Volume resuscitation\n- NaCl 0.9 % 10-20 мл/кг IV bolus\n- Repeat × 2-3 prn (max 60 мл/кг first hour)\n\n### Step 4: Adjuncts\n- **Corticosteroids:** methylprednisolone 1-2 мг/кг IV OR hydrocortisone 1-2 мг/кг IV (delayed onset, prevents biphasic)\n- **Antihistamines:** diphenhydramine 1 мг/кг IV/IM (H1 — secondary к epi)\n- **Bronchodilators:** salbutamol nebulized 0.1-0.3 мг/кг для bronchospasm\n- **Vasopressors continuous** при refractory shock: norepinephrine 0.05-1 мкг/кг/мин\n\n## Triggering drug discontinuation\n\n- Stop suspected drug immediately\n- Document trigger в medical record (allergy alert)\n- Future avoidance + parent education\n\n## Biphasic reaction prevention\n\n- 5-15 % anaphylaxis recurs 1-72 ч after initial\n- Observe ≥ 4-6 ч after resolution\n- Severe initial reactions — observe ≥ 24 ч\n- Discharge с epinephrine auto-injector planning (rare у newborn)\n\n## Calculator Bordik\n- neo-epinephrine-infusion (continuous IV)\n- neo-hydrocortisone-dose\n- neo-diphenhydramine-dose\n- neo-albuterol-nebulizer-dose\n\n## Источники\n- Simons FE et al. World Allergy Organ J 2011;4:13\n- AAP — Anaphylaxis 2024\n- Lieberman P et al. Ann Allergy Asthma Immunol 2015;115:341",
      ["Simons FE et al. World Allergy Organ J 2011;4:13", "Lieberman P et al. Ann Allergy 2015;115:341"]),

    g("guide_thrombocytopenia_management", "Thrombocytopenia у новорождённого",
      "Neonatal Thrombocytopenia Management",
      "metabolic",
      "## Definition + epidemiology\n\n- **Mild:** 100-149 × 10⁹/л\n- **Moderate:** 50-99 × 10⁹/л\n- **Severe:** < 50 × 10⁹/л\n- **Very severe:** < 20 × 10⁹/л\n\nIncidence: ~1-5 % всех newborns; up to 25 % у NICU patients.\n\n## Categories по timing\n\n### Early-onset (< 72 h)\n- **Maternal causes:** preeclampsia/HELLP, antibodies (NAIT, ITP), infection (TORCH)\n- **Placental insufficiency:** IUGR, fetal hypoxia\n- **NAIT** (Neonatal Alloimmune) — anti-HPA-1a most common\n- **Sepsis**\n\n### Late-onset (> 72 h)\n- **Sepsis** (most common — bacterial, fungal)\n- **NEC**\n- **Drug-induced** (heparin → HIT rare у newborn, vancomycin, ranitidine)\n- **CMV, TORCH late presentations**\n- **Thrombosis** (consumption)\n- **Bone marrow infiltration** (TAR syndrome, congenital leukemia rare)\n\n## NAIT (Neonatal Alloimmune Thrombocytopenia)\n\n### Pathophysiology\n- Maternal antibodies against fetal platelet antigens (HPA-1a most common — 75-85 %)\n- Crosses placenta — destroys fetal platelets\n- Severe thrombocytopenia frequently (< 30)\n- ICH risk до 20 % untreated\n\n### Treatment\n- **Maternal или HPA-matched platelets** (preferred — won't be destroyed by maternal antibodies)\n- **IVIG 1 г/кг daily × 2-5 d** (blocks Fc receptors)\n- **Random-donor platelets** as bridge until matched available\n- **Prednisone** controversial у newborn\n\n### Future pregnancies\n- Maternal IVIG + steroids в pregnancy (start ~20 нед)\n- Cesarean delivery preferred\n\n## Treatment thresholds platelet transfusion (PlaNeT-2 RCT 2019)\n\n### Restrictive (preferred — better outcomes)\n- **Symptomatic bleeding:** transfuse при ANY platelet count\n- **Asymptomatic stable:** transfuse при < 25 × 10⁹/л\n- **Asymptomatic + risk факторы** (MV severe, sepsis, NEC, IVH, surgery в next 12-24 ч): transfuse при < 50 × 10⁹/л\n- **Pre-procedure** (LP, surgery): < 50\n\n### Volume + rate\n- 10-15 мл/кг platelet concentrate over 30-60 мин\n- 1 unit (60 мл) → ~50,000 ↑ для term newborn\n- ABO-compatible preferred; HLA-matched при NAIT\n\n## Workup\n\n- **Maternal platelet count + history**\n- **NAIT testing:** maternal HPA antibodies\n- **CBC, retics, peripheral smear**\n- **Coag panel** (DIC?)\n- **Septic workup** (если suspected)\n- **TORCH screen**\n- **Cranial US** (ICH risk у severe)\n- **Bone marrow** (rare cases — congenital absence)\n\n## Calculator Bordik\n- neo-intravenous_immune_globulin_ivig (IVIG dose)\n- neo-perinatal-infections-class\n- neo-papile (IVH)\n\n## Источники\n- Curley A et al. NEJM 2019;380:242 — PlaNeT-2\n- Sola-Visner M. Hematology Am Soc Hematol Educ Program 2012\n- Roberts I. Br J Haematol 2008;141:312",
      ["Curley A et al. NEJM 2019;380:242 — PlaNeT-2", "Sola-Visner M. Hematology 2012", "Roberts I. Br J Haematol 2008;141:312"]),
]


def main():
    with JSON_PATH.open(encoding="utf-8") as f:
        data = json.load(f)
    existing = {p["id"] for p in data["guidelines"]}
    added = 0
    for p in NEW:
        if p["id"] in existing: continue
        # Schema requires references — already provided
        data["guidelines"].append(p)
        added += 1
    data["version"] = "1.6.0"
    data["lastUpdated"] = "2026-05-10"
    with JSON_PATH.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, separators=(",", ":"))
    print(f"Added {added} protocols. Total: {len(data['guidelines'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
