# ============================================================
# Bordik Med — Append commit info to a daily session log.
#
# Triggered by: git post-commit hook (after graphify, before vault sync).
# Output: docs/sessions/YYYY-MM-DD-auto.md (appended, idempotent).
#
# What gets logged per commit:
#   - SHA, subject, time
#   - Stats (files / +/- LOC)
#   - List of files changed
#   - Body (if commit has multiline message)
#
# Format compatible with existing _template.md structure so Obsidian
# vault picks it up via sync-vault.ps1 → vault\sessions\.
#
# Idempotent: if a session entry for the current SHA already exists in
# today's file, exits silently (no duplicate).
# ============================================================

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot
$SessionsDir = Join-Path $RepoRoot 'docs\sessions'

if (-not (Test-Path $SessionsDir)) {
    New-Item -ItemType Directory -Force -Path $SessionsDir | Out-Null
}

# Force UTF-8 output (some commits have Cyrillic subjects)
[Console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
$OutputEncoding = [System.Text.UTF8Encoding]::new()

# Read HEAD commit metadata (use git --no-pager to avoid ANSI/blocking).
function Run-Git {
    param([Parameter(ValueFromRemainingArguments)] [string[]] $args)
    $stdoutBytes = & git.exe @args 2>$null
    if ($LASTEXITCODE -ne 0) { return '' }
    if ($stdoutBytes -is [array]) { return ($stdoutBytes -join "`n") }
    return [string]$stdoutBytes
}

$sha = (Run-Git rev-parse --short HEAD).Trim()
if (-not $sha) { exit 0 }

$shaFull = (Run-Git rev-parse HEAD).Trim()
$subject = (Run-Git log -1 --format=%s HEAD).Trim()
$body    = (Run-Git log -1 --format=%b HEAD).Trim()
$author  = (Run-Git log -1 --format='%an' HEAD).Trim()

# ISO timestamp of the commit itself, not "now" — keeps logs accurate
# even if the hook runs after a delay (e.g. retried push).
$commitISO = (Run-Git log -1 --format=%cI HEAD).Trim()
try {
    $commitDT = [DateTimeOffset]::Parse($commitISO)
    $date = $commitDT.LocalDateTime.ToString('yyyy-MM-dd')
    $time = $commitDT.LocalDateTime.ToString('HH:mm')
} catch {
    $date = (Get-Date).ToString('yyyy-MM-dd')
    $time = (Get-Date).ToString('HH:mm')
}

$sessionFile = Join-Path $SessionsDir "$date-auto.md"

# Idempotent: skip if this SHA already logged.
# Short SHA appears inside `### \`<sha>\`` heading (что мы пишем в
# Md-Entry ниже). Full SHA в тело файла не попадает.
if (Test-Path $sessionFile) {
    $existing = Get-Content -Raw -Encoding UTF8 $sessionFile
    $marker = '### `' + $sha + '`'
    if ($existing.Contains($marker)) {
        # Already logged — silent exit
        exit 0
    }
}

# Stats: shortstat one-liner ("12 files changed, 145 insertions(+), 67 deletions(-)")
$stat = (Run-Git log -1 --shortstat --format= HEAD).Trim()
if (-not $stat) { $stat = '(no file changes)' }

# Files changed (cap at 50 to keep entries manageable)
$filesRaw = (Run-Git log -1 --name-only --format= HEAD).Trim()
$filesList = $filesRaw -split "`n" | Where-Object { $_.Trim() -ne '' }
$filesCount = $filesList.Count
$filesShown = $filesList | Select-Object -First 50
$truncated = $filesCount -gt 50

# Build markdown for this entry (NO leading whitespace on heredoc — must be col 0)
function Md-Entry {
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("### ``$sha``  $time  $author")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("**$subject**")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('```')
    [void]$sb.AppendLine($stat)
    [void]$sb.AppendLine('```')
    [void]$sb.AppendLine('')

    if ($body) {
        [void]$sb.AppendLine('<details><summary>Commit body</summary>')
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('```')
        [void]$sb.AppendLine($body)
        [void]$sb.AppendLine('```')
        [void]$sb.AppendLine('')
        [void]$sb.AppendLine('</details>')
        [void]$sb.AppendLine('')
    }

    [void]$sb.AppendLine("<details><summary>Files ($filesCount)</summary>")
    [void]$sb.AppendLine('')
    foreach ($f in $filesShown) {
        [void]$sb.AppendLine("- ``$f``")
    }
    if ($truncated) {
        [void]$sb.AppendLine("- _… ($($filesCount - 50) more, truncated)_")
    }
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('</details>')
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine('---')
    return $sb.ToString()
}

if (-not (Test-Path $sessionFile)) {
    # First commit of the day — write header
    $header = @"
---
title: Auto session log $date
date: $date
status: in-progress
type: auto-commit-log
tags: [auto, commits]
---

# Auto session log $date

> Generated by ``scripts/append-session.ps1`` on each commit. One entry per commit:
> SHA, subject, stat, body, files. Synced to Obsidian vault by ``sync-vault.ps1``.

## Commits

"@
    Set-Content -Path $sessionFile -Value $header -Encoding UTF8 -NoNewline
}

# Append entry
Add-Content -Path $sessionFile -Value (Md-Entry) -Encoding UTF8

# Quiet success — graphify hook is verbose enough already
exit 0
