"""
Build /public/neonatal-procedure-checklists.json — Таблица 3.Д5.

10 step-by-step чек-листов для bedside процедур. Структура:
- preparation (что подготовить — equipment, drugs, monitoring)
- before_procedure (verify/consent/team)
- during_procedure (sequential steps)
- after_procedure (monitoring, documentation, complications)
- references

Stateful UI — каждая позиция в чек-листе renderable как checkbox с
localStorage persistence (rendered в ChecklistCard).
"""
from __future__ import annotations
import json
from pathlib import Path

PATH = Path(r"C:\Users\KDFX Modes\Desktop\bordik-med\public\neonatal-procedure-checklists.json")


def chk(
    cid: str, title_ru: str, title_en: str, category: str, est_minutes: int,
    audience: str, indications: list[str],
    sections: list[dict], references: list[str],
) -> dict:
    return {
        "id": cid,
        "title_ru": title_ru,
        "title_en": title_en,
        "category": category,
        "estimated_minutes": est_minutes,
        "audience": audience,
        "indications": indications,
        "sections": sections,
        "references": references,
    }


def section(title: str, items: list[str]) -> dict:
    return {"title": title, "items": items}


CHECKLISTS = [
    chk(
        "checklist-uvc-placement",
        "Постановка пупочного венозного катетера (UVC)",
        "Umbilical Venous Catheter (UVC) placement",
        "vascular_access", 20, "Врач-неонатолог",
        ["Реанимация в родзале (быстрый IV-доступ)",
         "Долгосрочный IV-доступ у preterm <32 нед",
         "Заменное переливание",
         "ELBW в первые часы жизни"],
        [
            section("Подготовка", [
                "UVC catheter 3.5 Fr (BW <1500 г) или 5 Fr (BW ≥1500 г)",
                "Стерильный набор: халат, перчатки, простыня с отверстием, антисептик",
                "Шприцы 5 мл и 10 мл, NaCl 0.9% gepариновый (1 ЕД/мл) для prime",
                "Шёлк 3-0 для фиксации, ножницы",
                "Стерильный измерительный шнур (длина = глубина введения)",
                "Pulse oximeter, ECG monitoring подключены",
                "Готовность к рентгенографии (verify position)",
            ]),
            section("Перед процедурой", [
                "Консультация и согласие родителей (если возможно)",
                "Time-out: имя ребёнка, GA, BW, indication, allergies",
                "Стерильные перчатки + халат + маска + cap всех участников",
                "Положение supine, conformidad zonе подмышками",
                "Аналгезия: sucrose 24% PO + non-nutritive sucking (или морфин 0.05-0.1 мг/кг при острой necessity)",
            ]),
            section("Расчёт глубины введения", [
                "По формуле Shukla: depth (cm) = (1.5 × BW(kg)) + 5.6",
                "Альтернатива: shoulder-umbilicus distance × 0.6 + 1 (для ductus venosus position)",
                "Цель: catheter tip в IVC выше диафрагмы (T9-T10 уровень)",
            ]),
            section("Процедура", [
                "Чистка пуповины антисептиком (хлоргексидин 2% / повидон-йод)",
                "Стерильное обкладывание поля",
                "Шёлковая лигатура у основания пуповины (NOT затягивать сильно)",
                "Срез пуповины ножницами 1-2 см от кожи",
                "Идентификация: 2 артерии (мелкие, толстостенные) + 1 вена (крупная, тонкостенная, обычно в 12 ч)",
                "Введение catheter prime'а NaCl heparин",
                "Aspirate blood для confirm intravascular position",
                "Insert до pre-measured depth",
                "При сопротивлении: НЕ форсировать, оттянуть на 1 см и попробовать снова",
                "Aspirate + flush 1 мл NaCl 0.9%",
                "Фиксация: lasso шов вокруг пуповины + tape ladder bridge",
            ]),
            section("После процедуры", [
                "Stat AP and lateral chest/abdomen X-ray",
                "Verify tip position: T9-T10 (IVC выше диафрагмы) — OK",
                "Если low (ниже диафрагмы → portal vein) — pull back",
                "Если high (right atrium) — pull back на 1-2 см",
                "Документация: GA/BW/indication/depth/X-ray confirmation/complications",
                "Routine catheter care: q24h dressing change при stable, q4h flush 0.5-1 мл NaCl",
                "Removal criteria: established peripheral access OR 7-14 дней (CDC infection control)",
            ]),
            section("Осложнения", [
                "Перфорация (heart, liver, vascular) — stat ECHO + вызов хирурга",
                "Catheter-associated bloodstream infection (CLABSI) — culture + ABX",
                "Portal vein thrombosis (high tip in portal system)",
                "Hepatic necrosis (low position в portal vein)",
                "Air embolism — patient supine, занять головой влево",
            ]),
        ],
        [
            "Shukla H, Ferrara A. Am J Dis Child 1986;140:786 — Shukla formula",
            "AAP COFN 2017 — Umbilical catheter placement recommendations",
            "CDC. Guidelines for the prevention of intravascular catheter-related infections. 2011",
        ],
    ),

    chk(
        "checklist-uac-placement",
        "Постановка пупочного артериального катетера (UAC)",
        "Umbilical Arterial Catheter (UAC) placement",
        "vascular_access", 20, "Врач-неонатолог",
        ["Continuous arterial BP monitoring у нестабильного ELBW/VLBW",
         "Frequent ABG sampling без артериальной venepuncture",
         "Exchange transfusion (combination с UVC)"],
        [
            section("Подготовка", [
                "UAC catheter 3.5 Fr (BW <1500 г) или 5 Fr (BW ≥1500 г)",
                "Стерильный набор + extra: heparinized prime (1 ЕД/мл), pressure transducer, monitor",
                "Шприцы 1 мл, 5 мл; NaCl 0.9% heparin",
                "Шёлк 3-0",
                "Pulse oximeter (нижняя конечность — мониторинг perfusion)",
                "Готовность к рентгенографии",
            ]),
            section("Перед процедурой", [
                "Time-out + consent",
                "Стерильная подготовка как для UVC",
                "Pre-procedure: pulse oximeter на ноге для оценки perfusion после",
                "Sucrose 24% PO + analgesia",
            ]),
            section("Расчёт глубины введения", [
                "Высокая позиция (T6-T9): depth = (3 × BW kg) + 9 = (BW × 3) + 9 см",
                "Низкая позиция (L3-L4): depth = BW + 7 см",
                "AAP preferred высокая позиция (lower thrombosis rate)",
            ]),
            section("Процедура", [
                "Идентификация артерий: 2 артерии в позиции 4 ч и 8 ч (часовая стрелка)",
                "Дилатация артерии iris forceps через тонкие движения",
                "Insert catheter к pre-measured depth",
                "Артерия более резистентна — pop при entering",
                "Aspirate pulsatile bright red blood — confirms arterial",
                "Flush с NaCl heparin 0.5-1 мл",
                "Фиксация",
            ]),
            section("После процедуры", [
                "X-ray: tip в T6-T9 (высокая) или L3-L4 (низкая)",
                "Pulse check лоwer extremity (perfusion check)",
                "Toe colour каждые 1-2 ч",
                "Connect pressure transducer + monitor",
                "Continuous infusion NaCl heparin 0.25-1 мл/час",
                "Documentation",
                "Removal: ASAP if не нужен (preferably <5-7 дней)",
            ]),
            section("Осложнения", [
                "Vasospasm нижней конечности — STAT removal если persistent ischemia",
                "Thromboembolism — anticoagulation решение individualized",
                "Перфорация",
                "Infection",
                "Hypertension",
            ]),
        ],
        [
            "AAP COFN 2017 — Umbilical catheter placement",
            "Barrington KJ. Cochrane 2000 — Umbilical artery catheter placement",
        ],
    ),

    chk(
        "checklist-intubation",
        "Эндотрахеальная интубация новорождённого",
        "Endotracheal intubation в neonate",
        "respiratory", 5, "Врач-неонатолог",
        ["Apnea / inadequate PPV",
         "Need для surfactant administration (если LISA не feasible)",
         "Stabilisation для transport",
         "Severe RDS / failed CPAP",
         "Diaphragmatic hernia — immediate intubation после рождения"],
        [
            section("Подготовка", [
                "ЭТТ: 2.5 mm (BW <1000 g), 3.0 mm (1000-2000 g), 3.5 mm (2000-3000 g), 4.0 mm (>3000 g)",
                "Лярингоскоп: Miller blade size 0 (preterm), size 1 (term)",
                "Suction (отсос) с давлением 100 мм рт. ст.",
                "Bag-mask + appropriate size mask",
                "End-tidal CO₂ detector (colorimetric или capnography)",
                "Stylet (опционально — для preterm часто помогает)",
                "Tape для фиксации",
                "Готовность к surfactant (если показан)",
            ]),
            section("Премедикация (selective)", [
                "Atropine 0.02 мг/кг IV (анти-vagal — снижает bradycardia)",
                "Опиоид: morphine 0.05-0.1 мг/кг IV или fentanyl 1-2 мкг/кг IV (slow push)",
                "Paralytic: rocuronium 0.6 мг/кг IV ИЛИ succinylcholine 1-2 мг/кг (RSI)",
                "Premedicated intubation reduces hypoxia/bradycardia/ICP rises",
                "Отступление: emergency intubation в родзале — без премед",
            ]),
            section("Перед процедурой", [
                "Time-out: имя ребёнка, indication, allergy, plan B (LMA если failed)",
                "Pre-oxygenation: PPV с FiO₂ 100% × 30-60 секунд",
                "Position: sniffing position (нейтральная шея с лёгким расширением, валик 2-3 см под плечи)",
                "Monitor: SpO₂ + ECG + HR auscultation",
                "Suction по необходимости (clear airway)",
            ]),
            section("Процедура", [
                "Open mouth right hand",
                "Insert лярингоскоп left hand, slide along tongue right side",
                "Lift epiglottis (Miller blade подlifts directly)",
                "Visualize голосовые связки",
                "Insert ЭТТ через cords до depth = weight (kg) + 6 см от lip",
                "Confirm placement: chest rise, equal breath sounds, СО₂ detector colour change yellow",
                "Tape secured",
                "Connect к ventilator или bag",
                "Stat chest X-ray для verify position (tip между Т1-Т3)",
            ]),
            section("Неудачная интубация (>30 секунд)", [
                "Stop, withdraw ЭТТ",
                "Bag-mask ventilation × 30-60 секунд",
                "Re-attempt после re-oxygenation",
                "Multiple failed attempts (>3) → call senior, consider LMA",
            ]),
            section("После процедуры", [
                "Auscultation: equal breath sounds bilaterally + over stomach",
                "ETT depth at lip — record",
                "Chest X-ray verify position — Т1-Т3 (above carina)",
                "Tape secure, anchor",
                "Continuous monitoring: SpO₂, ETCO₂, HR, RR",
                "Documentation: tube size, depth at lip, X-ray confirmation, attempts, complications",
            ]),
            section("Осложнения", [
                "Hypoxia / bradycardia — extubate если HR <100 не отвечает на чистку tube",
                "Esophageal intubation — capnography no colour change → re-intubate",
                "Right main bronchus — pull back 0.5-1 см",
                "Trauma airway / dental injury",
                "Pneumothorax (через долгое время)",
            ]),
        ],
        [
            "Aziz K et al. Pediatrics 2021;147:e2020038505E — NRP 8 ed.",
            "Kumar P et al. Pediatrics 2010;125:e1606 — Premedication for Nonemergent Endotracheal Intubation",
        ],
    ),

    chk(
        "checklist-lp-neonatal",
        "Люмбальная пункция новорождённого",
        "Lumbar puncture в neonate",
        "neuro", 15, "Врач-неонатолог",
        ["Suspected meningitis (часть EOS/LOS work-up + clinical signs)",
         "Persistent positive blood culture",
         "Seizures без obvious cause",
         "Therapeutic LP при post-hemorrhagic hydrocephalus"],
        [
            section("Подготовка", [
                "Spinal needle 22-24 G × 1.5\" (preterm) или 22 G × 1.5-2\" (term)",
                "Стерильный набор: халат, перчатки, маска, сap, drape с отверстием",
                "Антисептик (хлоргексидин 2% или повидон-йод)",
                "3-4 sterile collection tubes (#1 culture, #2 cell count, #3 chemistry, #4 PCR/special)",
                "Manometer (опционально — opening pressure)",
                "Pulse oximeter, ECG monitoring",
            ]),
            section("Перед процедурой", [
                "Stat ABCs: stable hemodynamics, no apnea, no compromise",
                "CONTRAindications: skin infection в lumbar area, severe coagulopathy, increased ICP signs (avoid LP), spina bifida",
                "Time-out + consent",
                "Premedication: sucrose 24% PO + non-nutritive sucking. Avoid opioids/sedatives if hemodynamically borderline",
                "Stat IV access если ещё нет",
            ]),
            section("Положение", [
                "Lateral decubitus с flexed hip-knee (curled position)",
                "ИЛИ sitting position в hands of assistant (легче для preterm)",
                "Avoid жёсткое разгибание шеи (compromise дыхательных путей)",
                "Identify L3-L4 interspace (intercristal line crosses spine ~L4)",
            ]),
            section("Процедура", [
                "Стерильная prep + drape",
                "Identify L3-L4 или L4-L5 interspace",
                "Local anesthesia: 1% lidocaine 0.1-0.3 мл если опытный — но часто омит у newborn",
                "Insert needle bevel parallel к dural fibers (longitudinal)",
                "Slow advance медленно через ligamentum flavum + dura",
                "Stylet remove каждые 1-2 mm после initial penetration",
                "Watch for CSF return",
                "Collect 0.5-1 мл в каждую пробирку (4 tubes если возможно)",
                "Re-insert stylet перед removing needle",
            ]),
            section("После процедуры", [
                "Hemostasis: pressure 30 секунд",
                "Sterile dressing",
                "Reposition ребёнка comfortable",
                "Monitor SpO₂, HR × 30 минут",
                "Document: opening pressure, appearance CSF (clear vs turbid vs xanthochromic vs bloody), volume collected, complications",
                "Stat send: cell count + diff, gram stain + culture, glucose, protein, lactate, PCR (HSV/enterovirus если показано)",
            ]),
            section("Интерпретация CSF", [
                "Normal newborn CSF: WBC ≤25/µL preterm, ≤19/µL term; protein 70-150 mg/dL term, до 290 preterm; glucose 70-90% blood",
                "Bacterial meningitis: WBC >100, protein >200, glucose <50% blood, neutrophil predominance, gram stain organisms",
                "Viral: lymphocyte predominance, normal или slight protein elevation",
                "Traumatic tap: blood в 1 пробирке, clearing к 4. Reduce WBC count by 1 на 500-1000 RBC",
            ]),
            section("Осложнения", [
                "Apnea / desaturation (особенно preterm) — abort если SpO₂ <85% несмотря на support",
                "Bleeding (epidural hematoma)",
                "Infection (meningitis from contamination)",
                "Spinal headache (rare у newborn)",
                "Traumatic tap (>1000 RBC) — repeat if results uninterpretable",
            ]),
        ],
        [
            "AAP COFN 2024 — Procedures for the Newborn",
            "Schreiner RL, Kleiman MB. J Pediatr 1979;94:259 — Normal CSF",
        ],
    ),

    chk(
        "checklist-surfactant-lisa",
        "Введение сурфактанта методом LISA",
        "LISA — Less Invasive Surfactant Administration",
        "respiratory", 10, "Врач-неонатолог",
        ["Preterm <32 нед на CPAP с PEEP ≥6",
         "FiO₂ требование >0.30 для maintain target SpO₂ 90-95%",
         "Spontaneous breathing maintained",
         "Hemodynamically stable"],
        [
            section("Подготовка", [
                "Surfactant: Curosurf (poractant alfa) 200 мг/кг = 2.5 мл/кг (preferred первая доза)",
                "LISA катетер: 4-5 Fr (Hobart, LISAcath, или modified feeding tube)",
                "Лярингоскоп Miller blade size 0",
                "Magill forceps (для guide катетера)",
                "Suction готов",
                "CPAP system continuous through procedure",
                "Atropine 0.02 мг/кг IV ready (анти-vagal)",
                "Monitoring: SpO₂, ECG, capnography ноздревой",
            ]),
            section("Перед процедурой", [
                "Pre-warm surfactant до room temperature 20-30 минут",
                "Aspirate surfactant в шприц",
                "Pre-measure катетер depth: NTL (nose-tragus length) + 1 ИЛИ 6 + weight (kg) cm от кончика",
                "Position infant supine, head в sniffing position",
                "Sucrose 24% PO 0.5 мл 2 минут до",
                "Administer atropine IV",
                "Continuous CPAP",
            ]),
            section("Процедура", [
                "Direct laryngoscopy с visualization vocal cords",
                "Pass thin LISA катетер через cords к pre-measured depth (Magill forceps optional)",
                "HOLD катетер в position",
                "Remove laryngoscope",
                "Continue CPAP via nasal interface",
                "Confirm catheter tip position: gentle aspiration (cough reflex или mild resistance)",
                "Slow injection surfactant через катетер: 4 aliquots over 30-60 seconds",
                "Pause briefly between aliquots (allow distribution)",
                "Watch для desaturation / bradycardia / apnea",
                "Total injection time 1-3 минут",
            ]),
            section("После процедуры", [
                "Remove катетер",
                "Continue CPAP — НЕ extubate to room air",
                "Monitor SpO₂, HR, RR closely first 30-60 minutes",
                "Wean FiO₂ aggressively as oxygenation improves (часто FiO₂ 0.30 → 0.21 за 30-60 минут)",
                "Если apnea / persistent desaturation после procedure → consider intubation + IPPV",
                "Documentation: dose, technique, response, complications",
            ]),
            section("Осложнения", [
                "Transient desaturation (most common, < 30 секунд) — pause + increase CPAP/FiO₂",
                "Bradycardia — atropine premedication снижает risk",
                "Reflux surfactant (poor efficacy) — verify катетер depth",
                "Pneumothorax (lower vs IPPV)",
                "Failed insertion — convert to INSURE (intubate + surfactant + extubate)",
            ]),
        ],
        [
            "Sweet DG et al. Neonatology 2023;120:3 — European Consensus 2022 RDS",
            "Aldana-Aguirre JC et al. Arch Dis Child Fetal Neonatal Ed 2017;102:F17 — meta-analysis LISA",
            "Kribs A et al. JAMA Pediatr 2015;169:723 — NINSAPP trial",
        ],
    ),

    chk(
        "checklist-exchange-transfusion",
        "Заменное переливание крови (DVET)",
        "Double volume exchange transfusion",
        "hepatic", 90, "Врач-неонатолог + медсестра",
        ["TSB at exchange threshold (см. AAP 2022 / NICE / КР РФ номограммы)",
         "Severe Rh / ABO ГБН с rapid TSB rise",
         "Acute bilirubin encephalopathy (kernicterus signs)"],
        [
            section("Подготовка", [
                "Кровь: O Rh-negative, совместимая с матерью + ребёнком, gamma-irradiated, leukoreduced",
                "Объём: 160 мл/кг (термин), 180 мл/кг (preterm) = double blood volume",
                "Pre-warm кровь до 37°C (NOT холодная — гипотермия + arrhythmia)",
                "UVC уже placed (preferred) ИЛИ peripheral arterial-venous combo",
                "Шприцы 5-10 мл (term), 3-5 мл (preterm)",
                "3-way stopcock",
                "Мониторинг: SpO₂, ECG, t°, BP, glucose, ionized Ca²⁺, K⁺",
                "Calcium gluconate 10% готов (1-2 мл/кг при hypocalcemia)",
                "Готовность к реанимации",
            ]),
            section("Перед процедурой", [
                "Stat lab: TSB, type, screen, DAT, CBC, glucose, ionized Ca²⁺, electrolytes, coags",
                "Consent родителей",
                "Time-out: имя, BW, indication, blood unit verified, allergies",
                "NPO 4 часа",
                "Stable temperature (incubator pre-warmed)",
                "Continuous monitoring connected",
                "Phototherapy CONTINUE through procedure",
            ]),
            section("Процедура (push-pull через UVC)", [
                "Aliquot size: 5-10 мл term, 3-5 мл preterm",
                "Withdraw aliquot из UVC over 30-60 секунд",
                "Replace equal aliquot fresh blood over 30-60 секунд",
                "Pause 30-60 секунд между циклами для adequate mixing",
                "Total target: 160 мл/кг term (typically 4 ml/kg/min average rate)",
                "Total time: 60-90 минут",
            ]),
            section("Мониторинг во время процедуры", [
                "Vital signs continuous",
                "Glucose q15 минут — risk hypoglycemia (heparinized blood + insulin response)",
                "Ionized Ca²⁺ q15-30 минут — risk hypocalcemia (citrate-bound Ca²⁺)",
                "K⁺ q15-30 минут — risk hyperkalemia (старая кровь)",
                "TSB before, halfway, after",
                "Temperature continuous",
                "Watch arrhythmia / bradycardia / hypotension",
            ]),
            section("После процедуры", [
                "Stat post-exchange labs: TSB, CBC, electrolytes, ionized Ca²⁺, glucose, coags",
                "Continue intensive PT",
                "Re-check TSB через 4-6 часов (rebound common — 50% original level)",
                "Repeat exchange может потребоваться если TSB снова достигает threshold",
                "Monitor для NEC × 48-72 часа (особенно у preterm)",
                "Documentation",
            ]),
            section("Осложнения", [
                "Cardiac arrhythmias — bradycardia от cold blood, hypocalcemia, hyperkalemia",
                "Hypoglycemia — D10 IV bolus 2 мл/кг при low BG",
                "Hypocalcemia — calcium gluconate 1-2 мл/кг slow IV",
                "Hyperkalemia (severe — washed RBC, exchange faster)",
                "Thrombocytopenia, coagulopathy",
                "NEC (5-10% риск у preterm)",
                "Air embolism — strict технику",
                "Mortality 0.5-1.0% общая",
            ]),
        ],
        [
            "Kemper AR et al. Pediatrics 2022;150:e2022058859 — AAP 2022 hyperbilirubinemia",
            "NICE Clinical Guideline CG98",
            "BAPM 2016 — Severe hyperbilirubinaemia framework",
        ],
    ),

    chk(
        "checklist-chest-tube",
        "Постановка дренажа при пневмотораксе",
        "Chest tube placement для pneumothorax",
        "respiratory", 15, "Врач-неонатолог",
        ["Tension pneumothorax (стрессовая декомпенсация)",
         "Pneumothorax >20% с respiratory compromise",
         "Persistent air leak"],
        [
            section("Подготовка", [
                "Chest tube: 8-10 Fr (preterm), 12 Fr (term)",
                "Trocar (некоторые предпочитают blunt dissection вместо)",
                "Стерильный набор: халат, перчатки, drape, антисептик",
                "Local anesthesia: lidocaine 1% (0.5 мл/кг макс)",
                "Шёлк 3-0 для фиксации + анкерный шов",
                "Underwater seal + suction system",
                "Stat C-X готов (после procedure)",
                "Pulse oximeter, ECG monitoring",
            ]),
            section("Emergency Needle Decompression (если tension)", [
                "Если жизнеугрожающее: needle decompression сначала, chest tube потом",
                "23G angiocath во 2-м межреберье midclavicular line",
                "Aspirate с шприцом — air return = pneumothorax confirmed",
                "Continue до chest tube placement",
            ]),
            section("Перед процедурой", [
                "Time-out + consent (если non-emergency)",
                "Position supine, slight tilt towards opposite side",
                "Identify safe triangle: anterior axillary line, 4th-5th intercostal space",
                "Sterile prep + drape",
                "Local anesthesia",
                "Premedication (sucrose, opioid PRN)",
            ]),
            section("Процедура (preferred — blunt dissection)", [
                "1-2 cm transverse incision над 5-м ребром (избегать neurovascular bundle ниже ребра)",
                "Blunt dissection через intercostal muscles вверх над ребром",
                "Pop через parietal pleura",
                "Insert chest tube без trocar (safer)",
                "Direct tube anteriorly + apically (для pneumothorax)",
                "Insert до 4-6 cm depth",
                "All sideholes inside thorax",
                "Connect to underwater seal с suction -10 до -15 cm H₂O",
            ]),
            section("После процедуры", [
                "Confirm placement: bubbles в underwater seal с inspiration",
                "Stat AP chest X-ray — verify tube position + lung expansion",
                "Anchor стих: silk 3-0 — purse-string + tape",
                "Sterile occlusive dressing",
                "Continuous monitoring: SpO₂, RR, HR, breath sounds",
                "Documentation: side, size, depth, X-ray confirmation, complications",
                "Removal criteria: no air leak × 24 часа + lung fully expanded на X-ray",
            ]),
            section("Осложнения", [
                "Lung perforation (особенно с trocar — preferred blunt dissection)",
                "Hemothorax (intercostal artery injury)",
                "Diaphragmatic injury (если too low)",
                "Subcutaneous emphysema",
                "Re-expansion pulmonary edema (rare)",
                "Tube blockage / dislodgement",
                "Infection",
            ]),
        ],
        [
            "AAP COFN 2024 — Procedures for the Newborn",
            "Wyman ML et al. J Perinatol 2007;27:481 — Chest tube outcomes",
        ],
    ),

    chk(
        "checklist-cpap-initiation",
        "Инициация CPAP в родзале",
        "CPAP initiation в delivery room",
        "respiratory", 5, "Врач-неонатолог",
        ["Spontaneous breathing premature <32 нед",
         "Mild RDS",
         "Apnea of prematurity",
         "Wean от ИВЛ post-extubation"],
        [
            section("Подготовка", [
                "T-piece resuscitator (preferred) или Bubble CPAP",
                "Nasal prongs или nasal mask (правильный размер: covers nostrils без leak, но не давит на septum)",
                "Heated humidifier, target 37°C, 100% relative humidity",
                "Pulse oximeter (pre-ductal — RH)",
                "Готовность для escalation (PPV если apnea)",
            ]),
            section("Перед процедурой", [
                "Position infant: sniffing position, avoid neck hyperextension",
                "Suction только при obstruction",
                "Если preterm <32 нед: plastic bag/wrap (thermal protection)",
            ]),
            section("Settings", [
                "PEEP старт 6 см H₂O (5-8 диапазон)",
                "FiO₂ старт: 21% термин, 21-30% preterm",
                "Heated humidified flow",
                "Monitoring SpO₂ непрерывно",
            ]),
            section("Целевые SpO₂ (pre-ductal)", [
                "1 минута: 60-65%",
                "5 минут: 80-85%",
                "10 минут: 85-95%",
                "Steady state preterm: 90-95% (BOOST/SUPPORT)",
            ]),
            section("Эскалация", [
                "Если SpO₂ <90% несмотря FiO₂ 0.30: increase PEEP к 7-8 см H₂O",
                "Если still <90% при PEEP 8 + FiO₂ 0.40: consider surfactant (LISA preferred)",
                "Apnea / inadequate breathing → PPV ± intubation",
                "Persistent SpO₂ <85% + retractions: rescue intubation + IPPV",
            ]),
            section("Мониторинг и документация", [
                "Continuous: SpO₂, HR, RR",
                "WoB assessment q1-2 часа: Silverman score",
                "ABG если concerning",
                "Documentation: настройки, FiO₂, response, escalation",
            ]),
            section("Осложнения", [
                "Nasal trauma / septal injury — proper prong size + repositioning",
                "Pneumothorax (rare на CPAP, но возможно при слишком высоком PEEP)",
                "Gastric distention (consider OG tube для decompression)",
                "Failed CPAP — early surfactant + escalation",
            ]),
        ],
        [
            "Sweet DG et al. Neonatology 2023;120:3",
            "Schmölzer GM et al. BMJ 2013;347:f5980",
        ],
    ),

    chk(
        "checklist-newborn-stabilization-ga30",
        "Стабилизация недоношенного GA 28-30 нед в первые 60 минут",
        "Golden hour stabilization GA 28-30 weeks",
        "resuscitation", 60, "Команда родзала + NICU",
        ["Plan delivery preterm 28-30 нед", "ELBW post-delivery"],
        [
            section("Подготовка к рождению (за 30 мин)", [
                "Команда: неонатолог, респираторный терапевт, медсестра NICU",
                "Стол с лучистым обогревом ON",
                "T° помещения ≥26°C, no draft",
                "Plastic bag/wrap для тела",
                "Шапочка готов",
                "T-piece resuscitator (PEEP 5, PIP 20-25, FiO₂ 0.30)",
                "Pulse oximeter — RH (pre-ductal)",
                "Monitoring leads",
                "UVC kit ready",
                "D10W IV ready, GIR 6-8 мг/кг/мин",
                "Surfactant (Curosurf 200 мг/кг) refrigerated, ready to warm",
            ]),
            section("Минута 0-5: Birth + initial stabilization", [
                "DCC ≥60 секунд если состояние позволяет",
                "Place baby в plastic bag/wrap БЕЗ обтирания",
                "Шапочка",
                "Pulse oximeter RH",
                "Initial assessment: tone, breathing, HR",
                "If apneic/HR <100: PPV via T-piece (PIP 20-25, PEEP 5, FiO₂ 0.30)",
                "If breathing well: CPAP PEEP 5-6 H₂O",
            ]),
            section("Минута 5-15: Respiratory + thermal", [
                "Target SpO₂: 5 мин = 80-85%, 10 мин = 85-95%",
                "Titrate FiO₂ к target",
                "Если FiO₂ >0.30 на CPAP: surfactant LISA",
                "Premedicate atropine 0.02 мг/кг IV",
                "Curosurf 200 мг/кг через тонкий катетер",
                "Continue CPAP",
                "Аксиллярная t° — target 36.5-37.5°C",
            ]),
            section("Минута 15-30: Vascular access", [
                "UVC placement (см. отдельный чек-лист)",
                "Stat blood: glucose, blood gas, electrolytes, CBC, blood culture",
                "Start D10W GIR 6 мг/кг/мин",
                "Aminoacids 1.5-2 г/кг/сут IV (early protein)",
                "Caffeine loading 20 мг/кг IV (универсально preterm)",
            ]),
            section("Минута 30-60: Transfer + monitoring", [
                "Transport в NICU в pre-warmed transport-incubator",
                "Continuous monitoring throughout",
                "Stat AP chest X-ray + abdomen (verify UVC + lung pathology)",
                "Family update — родители informed",
                "Documentation: timing, interventions, outcomes",
            ]),
        ],
        [
            "Stranak Z et al. Resuscitation 2020 — Golden hour neonatal",
            "Sweet DG et al. Neonatology 2023;120:3",
            "Aziz K et al. Pediatrics 2021;147:e2020038505E",
        ],
    ),

    chk(
        "checklist-th-cooling-init",
        "Инициация терапевтической гипотермии (TH)",
        "Therapeutic hypothermia (TH) initiation",
        "neuro", 30, "NICU team",
        ["GA ≥36 нед, BW ≥1800 г",
         "Apgar ≤5 на 10 мин ИЛИ ИВЛ ≥10 мин ИЛИ pH<7.0 ИЛИ BD≥16",
         "Sarnat II-III (умеренная-тяжёлая HIE)",
         "В первые 6 часов от рождения"],
        [
            section("Перед началом — eligibility", [
                "Verify GA ≥36 нед + BW ≥1800 г",
                "Confirm criteria A: Apgar ≤5 на 10 мин ИЛИ ИВЛ ≥10 мин ИЛИ pH ≤7.0 ИЛИ BD ≥16 ммоль/л",
                "Confirm criteria B: Sarnat exam — moderate / severe encephalopathy",
                "Verify time from birth: первые 6 часов",
                "EXCLUDE: lethal anomaly, intractable bleeding, severe head trauma, weight <1800 g",
                "Consent родителей (если возможно — может быть emergent)",
            ]),
            section("Подготовка", [
                "Cooling device (whole-body cooling blanket) prepped",
                "Rectal probe для core t° monitoring",
                "Ventilator support готов (часто intubation indicated)",
                "Continuous aEEG/EEG monitoring",
                "Multiple IV access",
                "Lab orders: ABG, electrolytes, glucose, lactate, coags, LFTs, CBC",
                "MRI scheduled day 4-7",
                "Cardiology consult если cardiac dysfunction",
            ]),
            section("Initiation procedure", [
                "Initial вакасс stat",
                "Intubation если apnea, persistent acidosis или need for ventilation",
                "Place rectal probe",
                "Start cooling blanket — target core 33-34°C × 72 часа",
                "Sedation: morphine 10-20 мкг/кг/час OR fentanyl 0.5-2 мкг/кг/час continuous (snizhayet shivering + hypertensive response)",
                "Avoid muscle relaxants routinely — masks seizures",
                "Anticonvulsants ready: phenobarbital 20 мг/кг IV bolus",
            ]),
            section("Мониторинг во время cooling (72 часа)", [
                "Core t° q15 min initial → q1h",
                "HR continuous (cooling-induced bradycardia 70-100 OK)",
                "BP continuous — MAP target ≥40 мм рт. ст.",
                "SpO₂ continuous — target 90-95%",
                "aEEG/EEG continuous — detect electrographic seizures (30-50% HIE)",
                "Glucose q1-2h — target 4-7 ммоль/л",
                "Electrolytes q4-6h",
                "ABG q4-6h",
                "Coags q12-24h",
                "Hb target ≥130 г/л — transfuse PRBC если low",
                "Skin checks q4h — risk pressure injury",
                "Strict input/output",
            ]),
            section("Rewarming (после 72 часов)", [
                "Slow rate ≤0.5°C / час",
                "Total rewarming time 6-12 часов",
                "Continuous monitoring (risk: seizures, hypoglycemia, hypotension, K+ shifts)",
                "После achieving 36.5°C — continue intensive monitoring × 24-48h",
                "Сontinue anticonvulsants (taper по seizure pattern)",
            ]),
            section("Outcomes assessment", [
                "MRI brain day 4-7 (DWI для ischemia)",
                "Continuous EEG для seizure activity through rewarming",
                "Formal neurological exam at discharge (Sarnat)",
                "Long-term: neurodevelopmental follow-up at 18-24 мес",
            ]),
        ],
        [
            "Shankaran S et al. NEJM 2005;353:1574 — NICHD trial",
            "Azzopardi DV et al. NEJM 2009;361:1349 — TOBY trial",
            "AAP/ACOG 2014 Joint Statement — Neonatal Encephalopathy",
        ],
    ),
]


def main() -> None:
    bank = {
        "version": "1.0.0",
        "lastUpdated": "2026-05-10",
        "source": "Bordik Med — Neonatology procedure checklists (audit Table 3.Д5)",
        "license": "Educational checklists adapted from public guidelines (AAP, NRP, NICE, AAP COFN, Cochrane).",
        "categories": [
            {"id": "vascular_access", "title_ru": "Сосудистый доступ"},
            {"id": "respiratory",     "title_ru": "Респираторные"},
            {"id": "neuro",           "title_ru": "Неврологические"},
            {"id": "hepatic",         "title_ru": "Гепатобилиарные"},
            {"id": "resuscitation",   "title_ru": "Реанимация"},
        ],
        "checklists": CHECKLISTS,
    }
    PATH.write_text(json.dumps(bank, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {len(CHECKLISTS)} checklists to {PATH.name}")


if __name__ == "__main__":
    main()
