'use client';

import { useEffect, useMemo, useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { modules } from '@/lib/curriculum';
import { useAppStore } from '@/lib/store';
import { log } from '@/lib/log';
import type {
  Turn,
  ServerQuestion,
  FinalResult,
  Phase,
} from '@/lib/diagnostic/types';
import { topicRu, levelRu, friendlyError } from '@/lib/diagnostic/utils';
import { Spinner } from './diagnostic/Spinner';
import { ListPanel } from './diagnostic/ListPanel';

/**
 * Adaptive diagnostic test. Each question is generated by Gemini based on
 * the user's previous answers. After 15 questions the AI produces a
 * personalised profession + module recommendation.
 *
 * Flow:
 *   loading → asking → (user picks) → reviewing → next →
 *   ... 15 turns ... → finalizing → done
 */
export default function DiagnosticTest({ onClose }: { onClose: () => void }) {
  const openCourse = useAppStore((s) => s.openCourse);
  const setLastDiagnosticResult = useAppStore((s) => s.setLastDiagnosticResult);
  const cachedResult = useAppStore((s) => s.lastDiagnosticResult);
  // Если у пользователя есть сохранённый результат — стартуем сразу с
  // экрана 'done'. Это даёт возможность вернуться к рекомендациям без
  // повторного прохождения 30 вопросов. Кнопка «Пройти заново»
  // обнуляет кеш и начинает с loading.
  const [phase, setPhase] = useState<Phase>(cachedResult ? 'done' : 'loading');
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  // P1-PERF-NEW-5 — streaming preview text (Gemini partial output) для
  // показа пользователю под spinner'ом в "finalizing" phase. Обновляется
  // по мере прихода chunks от /api/diagnostic NDJSON stream.
  const [streamingPreview, setStreamingPreview] = useState<string>('');
  const [history, setHistory] = useState<Turn[]>([]);
  const [current, setCurrent] = useState<ServerQuestion | null>(null);
  const [picked, setPicked] = useState<number | null>(null);
  const [final, setFinal] = useState<FinalResult | null>(
    cachedResult
      ? {
          profession: cachedResult.profession,
          professionRationale: cachedResult.professionRationale,
          level: cachedResult.level,
          strengths: cachedResult.strengths,
          weaknesses: cachedResult.weaknesses,
          recommendedModuleIds: cachedResult.recommendedModuleIds,
          studyPlan: cachedResult.studyPlan,
        }
      : null,
  );

  /** Compact module summaries for the finalize prompt (id + title + desc). */
  const moduleSummaries = useMemo(() => {
    return modules.map((m) => ({
      id: m.id,
      sectionId: m.sectionId,
      title: m.title,
      description: m.description ?? '',
    }));
  }, []);

  const fetchNext = useCallback(async (h: Turn[]) => {
    setPhase('loading');
    setErrorMsg(null);

    // One automatic retry-with-backoff on transient errors. The diagnostic
    // depends on a chain of API calls; a single 429 from Google's free
    // quota during a rolling wave of users would otherwise force the user
    // to manually click "Попробовать снова" repeatedly. We do exactly one
    // silent retry after a 2.5s wait so the user never sees the toast for
    // brief upstream blips.
    let attempt = 0;
    while (attempt < 2) {
      try {
        const r = await fetch('/api/diagnostic', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ action: 'next', history: h }),
        });
        const json = await r.json();
        if (r.ok && json.ok) {
          setCurrent(json as ServerQuestion);
          setPicked(null);
          setPhase('asking');
          return;
        }
        const code = json?.error || `http-${r.status}`;
        const f = friendlyError(code);
        if (attempt === 0 && f.retryable) {
          attempt++;
          await new Promise((res) => setTimeout(res, 2500));
          continue;
        }
        // P2-NEW-12 — структурный лог через lib/log с redaction.
        log.error({ event: 'diagnostic_next_failed', code });
        setErrorMsg(f.msg);
        setPhase('error');
        return;
      } catch (err) {
        if (attempt === 0) {
          attempt++;
          await new Promise((res) => setTimeout(res, 2500));
          continue;
        }
        log.error({
          event: 'diagnostic_next_threw',
          message: (err as Error)?.message ?? String(err).slice(0, 200),
        });
        setErrorMsg('Нет связи с сервером. Проверьте интернет.');
        setPhase('error');
        return;
      }
    }
  }, []);

  const finalize = useCallback(async (h: Turn[]) => {
    setPhase('finalizing');
    setErrorMsg(null);
    setStreamingPreview(''); // P1-PERF-NEW-5 — reset preview on each attempt
    // Same one-shot retry pattern as fetchNext — finalize is a single
    // expensive call that summarises all 30 turns; we'd rather wait 2.5s
    // and retry than burn the whole completed test on a transient 429.
    let attempt = 0;
    while (attempt < 2) {
      try {
        // P1-PERF-NEW-5 — request streaming response. Server returns
        // application/x-ndjson с строками { type: 'chunk' | 'done', ... }.
        // Каждый 'chunk' даёт accumulated raw text от Gemini, чтобы UI
        // мог показать live preview ("анализирую...") вместо blank
        // spinner на 3-8 секунд. На любую ошибку streaming server emit'ит
        // 'done' с rule-based fallback — UX никогда не падает.
        const r = await fetch('/api/diagnostic', {
          method: 'POST',
          headers: {
            'content-type': 'application/json',
            'accept': 'application/x-ndjson',
          },
          body: JSON.stringify({ action: 'finalize', history: h, modules: moduleSummaries }),
        });

        // Streaming path: read NDJSON line by line.
        if (r.ok && r.body && r.headers.get('content-type')?.includes('application/x-ndjson')) {
          const reader = r.body.pipeThrough(new TextDecoderStream()).getReader();
          let buf = '';
          let finalResult: FinalResult | null = null;
          for (;;) {
            const { done, value } = await reader.read();
            if (done) break;
            buf += value;
            let idx;
            while ((idx = buf.indexOf('\n')) >= 0) {
              const line = buf.slice(0, idx).trim();
              buf = buf.slice(idx + 1);
              if (!line) continue;
              try {
                const evt = JSON.parse(line) as { type: string; text?: string; result?: FinalResult };
                if (evt.type === 'chunk' && typeof evt.text === 'string') {
                  setStreamingPreview(evt.text);
                } else if (evt.type === 'done' && evt.result) {
                  finalResult = evt.result;
                }
              } catch { /* skip malformed line */ }
            }
          }
          if (finalResult) {
            setFinal(finalResult);
            setPhase('done');
            setLastDiagnosticResult({
              ...finalResult,
              correct: h.filter((t) => t.selectedIndex === t.correctIndex).length,
              total: h.length,
              completedAt: new Date().toISOString(),
            });
            return;
          }
          // Stream ended without 'done' event — treat as transient
          throw new Error('stream-ended-without-result');
        }

        // Fallback: non-streaming JSON response (server didn't honor ndjson Accept)
        const json = await r.json();
        if (r.ok && json.ok) {
          const result = json as FinalResult;
          setFinal(result);
          setPhase('done');
          // Persist в стор: пользователь может закрыть и вернуться,
          // или открыть на другом устройстве (через Supabase-sync).
          // correctSoFar/history.length считаются ниже в render —
          // здесь читаем актуальные значения из state через get().
          setLastDiagnosticResult({
            ...result,
            correct: h.filter((t) => t.selectedIndex === t.correctIndex).length,
            total: h.length,
            completedAt: new Date().toISOString(),
          });
          return;
        }
        const code = json?.error || `http-${r.status}`;
        const f = friendlyError(code);
        if (attempt === 0 && f.retryable) {
          attempt++;
          await new Promise((res) => setTimeout(res, 2500));
          continue;
        }
        setErrorMsg(f.msg);
        setPhase('error');
        return;
      } catch {
        if (attempt === 0) {
          attempt++;
          await new Promise((res) => setTimeout(res, 2500));
          continue;
        }
        setErrorMsg('Нет связи с сервером. Проверьте интернет.');
        setPhase('error');
        return;
      }
    }
  }, [moduleSummaries]);

  // Kick off the first question on mount, но только если нет
  // cached-результата. С cached — сразу показываем 'done' (см. setPhase
  // в useState инициализаторе выше) и не дёргаем API.
  useEffect(() => {
    if (cachedResult) return;
    fetchNext([]);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handlePick = (idx: number) => {
    if (phase !== 'asking' || !current) return;
    setPicked(idx);
    setPhase('reviewing');
  };

  const handleNext = () => {
    if (!current || picked == null) return;
    const turn: Turn = {
      question: current.question,
      options: current.options,
      correctIndex: current.correctIndex,
      selectedIndex: picked,
      topic: current.topic,
      explanation: current.explanation,
    };
    const newHistory = [...history, turn];
    setHistory(newHistory);
    if (newHistory.length >= current.total) {
      finalize(newHistory);
    } else {
      fetchNext(newHistory);
    }
  };

  const restart = () => {
    setHistory([]);
    setCurrent(null);
    setPicked(null);
    setFinal(null);
    // Очищаем сохранённый результат — пользователь явно сказал
    // «Пройти заново», старые рекомендации больше не актуальны.
    setLastDiagnosticResult(null);
    setPhase('loading');
    fetchNext([]);
  };

  const total = current?.total ?? 30;
  const indexNow = current?.index ?? history.length;
  const progressPct = Math.round((indexNow / total) * 100);
  const correctSoFar = history.filter((t) => t.selectedIndex === t.correctIndex).length;

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25, ease: [0.05, 0.7, 0.1, 1] }}
      style={{ maxWidth: 760, margin: '0 auto', padding: '0 var(--space-4)' }}
    >
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 18 }}>
        <button
          onClick={onClose}
          aria-label="Закрыть"
          style={{
            width: 36, height: 36, borderRadius: 10,
            background: '#F5F6F8', color: '#1A1A1A', border: 'none',
            cursor: 'pointer',
            display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
            transition: 'background 150ms',
          }}
          onMouseEnter={(e) => { e.currentTarget.style.background = '#E8E9ED'; }}
          onMouseLeave={(e) => { e.currentTarget.style.background = '#F5F6F8'; }}
        >
          <svg width={16} height={16} viewBox="0 0 24 24" fill="none"
            stroke="currentColor" strokeWidth={2.2} strokeLinecap="round" strokeLinejoin="round">
            <line x1="19" y1="12" x2="5" y2="12" />
            <polyline points="12 19 5 12 12 5" />
          </svg>
        </button>
        <div style={{ flex: 1 }}>
          <p style={{
            margin: 0,
            fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 600,
            color: '#9CA3AF', textTransform: 'uppercase', letterSpacing: '0.08em',
          }}>
            Диагностика
          </p>
          <h2 style={{
            margin: '2px 0 0',
            fontFamily: 'var(--font-display)', fontSize: 22, fontWeight: 700,
            color: '#1A1A1A', letterSpacing: '-0.02em', lineHeight: 1.2,
          }}>
            Адаптивный тест уровня знаний
          </h2>
        </div>
      </div>

      {/* Progress bar */}
      {phase !== 'done' && phase !== 'error' && (
        <div style={{ marginBottom: 22 }}>
          <div style={{
            display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
            marginBottom: 6,
          }}>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: '#6B7280' }}>
              {phase === 'finalizing'
                ? 'Собираем рекомендацию…'
                : `Вопрос ${Math.min(indexNow + 1, total)} из ${total}`}
            </span>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: '#9CA3AF' }}>
              {correctSoFar}/{history.length} верных
            </span>
          </div>
          <div style={{
            height: 6, borderRadius: 999, background: '#F1F3F6', overflow: 'hidden',
          }}>
            <motion.div
              animate={{ width: `${progressPct}%` }}
              transition={{ duration: 0.4, ease: [0.05, 0.7, 0.1, 1] }}
              style={{ height: '100%', background: '#2563EB', borderRadius: 999 }}
            />
          </div>
        </div>
      )}

      {/* Body */}
      <AnimatePresence mode="wait">
        {phase === 'loading' && (
          <motion.div key="loading" {...fadeProps} style={panelStyle}>
            <Spinner />
            <p style={loadingTextStyle}>Готовим следующий вопрос…</p>
          </motion.div>
        )}

        {phase === 'finalizing' && (
          <motion.div key="finalizing" {...fadeProps} style={panelStyle}>
            <Spinner />
            <p style={loadingTextStyle}>Анализируем ответы и собираем рекомендацию…</p>
            {/* P1-PERF-NEW-5 — streaming preview: показываем raw text от
                Gemini по мере прихода chunks. Truncate первые 240 chars
                чтобы UI не «прыгал» при разрастании текста. Опционально —
                есть только если streamingPreview непустое (т.е. сервер
                действительно вернул NDJSON и chunk'и приходят). */}
            {streamingPreview.length > 20 && (
              <p style={{
                marginTop: 14,
                padding: '10px 14px',
                background: '#F5F6F8',
                borderRadius: 10,
                fontFamily: 'var(--font-mono, ui-monospace)',
                fontSize: 11.5,
                color: '#6B7280',
                lineHeight: 1.5,
                maxWidth: 480,
                fontStyle: 'italic',
                opacity: 0.85,
                // Truncate visually — не показываем больше 240 chars,
                // последние 240 chars (живой "хвост" generation'а).
                overflow: 'hidden',
                textOverflow: 'ellipsis',
                display: '-webkit-box',
                WebkitLineClamp: 3,
                WebkitBoxOrient: 'vertical',
              }}>
                {streamingPreview.length > 240
                  ? '…' + streamingPreview.slice(-240)
                  : streamingPreview}
              </p>
            )}
          </motion.div>
        )}

        {phase === 'error' && (
          <motion.div key="error" {...fadeProps} style={{
            ...panelStyle, background: '#F5F6F8',
          }}>
            <p style={{
              fontFamily: 'var(--font-body)', fontSize: 14, fontWeight: 600,
              color: '#1A1A1A', marginBottom: 6,
              display: 'inline-flex', alignItems: 'center', gap: 8,
            }}>
              <span style={{
                width: 8, height: 8, borderRadius: 999,
                background: '#F87171', display: 'inline-block',
              }} />
              Что-то пошло не так
            </p>
            <p style={{
              fontFamily: 'var(--font-body)', fontSize: 13, color: '#4B5563',
              lineHeight: 1.5, marginBottom: 14,
            }}>
              {errorMsg ?? 'Неизвестная ошибка.'}
            </p>
            <div style={{ display: 'flex', gap: 8 }}>
              <button onClick={() => fetchNext(history)} style={primaryBtn}>
                Попробовать снова
              </button>
              <button onClick={onClose} style={secondaryBtn}>Закрыть</button>
            </div>
          </motion.div>
        )}

        {(phase === 'asking' || phase === 'reviewing') && current && (
          <motion.div key={`q-${indexNow}`} {...fadeProps} style={panelStyle}>
            <p style={{
              fontFamily: 'var(--font-mono)', fontSize: 10, fontWeight: 700,
              color: '#9CA3AF', textTransform: 'uppercase', letterSpacing: '0.08em',
              margin: '0 0 8px',
            }}>
              Тема · {topicRu(current.topic)}
            </p>
            <h3 style={{
              fontFamily: 'var(--font-display)', fontSize: 18, fontWeight: 700,
              color: '#1A1A1A', letterSpacing: '-0.01em', lineHeight: 1.35,
              margin: '0 0 18px',
            }}>
              {current.question}
            </h3>
            <ul style={{ margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 10 }}>
              {current.options.map((opt, i) => {
                const isPicked = picked === i;
                const isReview = phase === 'reviewing';
                const isCorrect = i === current.correctIndex;
                let bg = '#F5F6F8';
                let border = 'none';
                let color = '#1A1A1A';
                if (isReview) {
                  if (isCorrect) { bg = '#ECFDF5'; border = '1px solid #A7F3D0'; color = '#065F46'; }
                  else if (isPicked) { bg = '#FEF2F2'; border = '1px solid #FCA5A5'; color = '#991B1B'; }
                } else if (isPicked) {
                  bg = '#EFF6FF'; border = '1px solid #BFDBFE'; color = '#1E40AF';
                }
                return (
                  <li key={i}>
                    <button
                      onClick={() => handlePick(i)}
                      disabled={isReview}
                      style={{
                        width: '100%', textAlign: 'left',
                        padding: '12px 16px', borderRadius: 12,
                        background: bg, border, color,
                        cursor: isReview ? 'default' : 'pointer',
                        fontFamily: 'var(--font-body)', fontSize: 14, lineHeight: 1.45,
                        display: 'flex', alignItems: 'flex-start', gap: 12,
                        transition: 'background 160ms, border-color 160ms, color 160ms',
                      }}
                      onMouseEnter={(e) => {
                        if (!isReview && !isPicked) e.currentTarget.style.background = '#E8E9ED';
                      }}
                      onMouseLeave={(e) => {
                        if (!isReview && !isPicked) e.currentTarget.style.background = '#F5F6F8';
                      }}
                    >
                      <span style={{
                        flexShrink: 0, marginTop: 2,
                        width: 22, height: 22, borderRadius: 6,
                        background: isReview && isCorrect ? '#10B981'
                          : isReview && isPicked ? '#DC2626'
                          : isPicked ? '#3B82F6'
                          : '#E2E4EA',
                        color: '#FFFFFF',
                        fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 700,
                        display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                      }}>
                        {String.fromCharCode(65 + i)}
                      </span>
                      <span style={{ flex: 1 }}>{opt}</span>
                    </button>
                  </li>
                );
              })}
            </ul>

            {phase === 'reviewing' && current.explanation && (
              <div style={{
                marginTop: 16, padding: '12px 14px',
                background: '#F8FAFC', borderRadius: 10,
                fontFamily: 'var(--font-body)', fontSize: 13, color: '#475569',
                lineHeight: 1.55,
              }}>
                <strong style={{ color: '#1A1A1A', display: 'block', marginBottom: 4 }}>Пояснение</strong>
                {current.explanation}
              </div>
            )}

            {phase === 'reviewing' && (
              <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 18 }}>
                <button onClick={handleNext} style={primaryBtn}>
                  {history.length + 1 >= total ? 'Получить рекомендацию' : 'Следующий вопрос →'}
                </button>
              </div>
            )}
          </motion.div>
        )}

        {phase === 'done' && final && (
          <motion.div key="done" {...fadeProps} style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
            {/* Hero card with profession — Bordik monochrome (no blue gradient).
                Same #F5F6F8 surface as section/module cards so the result
                page reads as part of the platform, not a foreign branded view. */}
            <div style={{
              padding: 'clamp(20px, 4vw, 32px)',
              background: '#F5F6F8',
              borderRadius: 18,
            }}>
              <p style={{
                margin: 0,
                fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 700,
                color: '#6B7280', textTransform: 'uppercase', letterSpacing: '0.08em',
              }}>
                Рекомендуемое направление
              </p>
              <h3 style={{
                margin: '8px 0 10px',
                fontFamily: 'var(--font-display)', fontSize: 28, fontWeight: 700,
                color: '#1A1A1A', letterSpacing: '-0.02em', lineHeight: 1.1,
              }}>
                {final.profession}
              </h3>
              <p style={{
                margin: 0,
                fontFamily: 'var(--font-body)', fontSize: 14, color: '#374151',
                lineHeight: 1.55,
              }}>
                {final.professionRationale}
              </p>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginTop: 14 }}>
                <span style={pillStyle}>Уровень: {levelRu(final.level)}</span>
                <span style={pillStyle}>{correctSoFar}/{history.length} верных ответов</span>
              </div>
            </div>

            {/* Strengths + weaknesses */}
            {(final.strengths.length > 0 || final.weaknesses.length > 0) && (
              <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
                gap: 14,
              }}>
                {final.strengths.length > 0 && (
                  <ListPanel title="Сильные стороны" tone="green" items={final.strengths} />
                )}
                {final.weaknesses.length > 0 && (
                  <ListPanel title="Над чем поработать" tone="amber" items={final.weaknesses} />
                )}
              </div>
            )}

            {/* Study plan */}
            {final.studyPlan && (
              <div style={{
                padding: '16px 18px', borderRadius: 14,
                background: '#FFFFFF', border: '1px solid #E5E7EB',
              }}>
                <p style={{
                  margin: 0,
                  fontFamily: 'var(--font-mono)', fontSize: 10, fontWeight: 700,
                  color: '#6B7280', textTransform: 'uppercase', letterSpacing: '0.08em',
                }}>
                  План обучения
                </p>
                <p style={{
                  margin: '6px 0 0',
                  fontFamily: 'var(--font-body)', fontSize: 14, color: '#1A1A1A',
                  lineHeight: 1.55,
                }}>
                  {final.studyPlan}
                </p>
              </div>
            )}

            {/* Recommended modules */}
            {final.recommendedModuleIds.length > 0 && (
              <div>
                <h4 style={{
                  margin: '0 0 12px',
                  fontFamily: 'var(--font-display)', fontSize: 16, fontWeight: 700,
                  color: '#1A1A1A',
                }}>
                  Рекомендуемые модули
                </h4>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {final.recommendedModuleIds.map((id, idx) => {
                    const mod = modules.find((m) => m.id === id);
                    if (!mod) return null;
                    return (
                      <button
                        key={id}
                        onClick={() => {
                          // Open the module - if it has courses, jump to the first one
                          if (mod.courses[0]) openCourse(mod.courses[0].id);
                        }}
                        style={{
                          textAlign: 'left',
                          display: 'flex', alignItems: 'center', gap: 14,
                          padding: '14px 16px',
                          background: '#F5F6F8', border: 'none',
                          borderRadius: 12, cursor: 'pointer',
                          transition: 'background 150ms',
                        }}
                        onMouseEnter={(e) => {
                          e.currentTarget.style.background = '#F0F2F5';
                        }}
                        onMouseLeave={(e) => {
                          e.currentTarget.style.background = '#F5F6F8';
                        }}
                      >
                        <span style={{
                          width: 32, height: 32, borderRadius: 10,
                          background: '#2563EB', color: '#FFFFFF',
                          display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                          fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 700,
                          flexShrink: 0,
                        }}>
                          {idx + 1}
                        </span>
                        <span style={{ flex: 1, minWidth: 0 }}>
                          <span style={{
                            display: 'block',
                            fontFamily: 'var(--font-body)', fontSize: 14, fontWeight: 600,
                            color: '#1A1A1A', lineHeight: 1.3,
                          }}>
                            {mod.title}
                          </span>
                          <span style={{
                            display: 'block', marginTop: 2,
                            fontFamily: 'var(--font-body)', fontSize: 12, color: '#6B7280',
                            lineHeight: 1.4,
                          }}>
                            {mod.description}
                          </span>
                        </span>
                        <svg width={14} height={14} viewBox="0 0 24 24" fill="none"
                          stroke="#9CA3AF" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round"
                          style={{ flexShrink: 0 }}>
                          <line x1="5" y1="12" x2="19" y2="12" />
                          <polyline points="12 5 19 12 12 19" />
                        </svg>
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Footer actions */}
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 6 }}>
              <button onClick={restart} style={secondaryBtn}>Пройти заново</button>
              <button onClick={onClose} style={primaryBtn}>Закрыть</button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

/* ───── helpers ───── */

const fadeProps = {
  initial: { opacity: 0, y: 8 },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: -6 },
  transition: { duration: 0.25, ease: [0.05, 0.7, 0.1, 1] as const },
};

const panelStyle = {
  background: '#FFFFFF',
  border: '1px solid #F0F1F5',
  borderRadius: 18,
  padding: 'clamp(20px, 4vw, 28px)',
};

const loadingTextStyle = {
  marginTop: 12,
  fontFamily: 'var(--font-body)',
  fontSize: 13,
  color: '#6B7280',
  textAlign: 'center' as const,
};

const primaryBtn: React.CSSProperties = {
  padding: '10px 20px', borderRadius: 10,
  background: '#2563EB', color: '#FFFFFF',
  border: 'none', cursor: 'pointer',
  fontFamily: 'var(--font-body)', fontSize: 13, fontWeight: 600,
  transition: 'background 180ms',
};

const secondaryBtn: React.CSSProperties = {
  padding: '10px 16px', borderRadius: 10,
  background: 'transparent', color: '#6B7280',
  border: 'none', cursor: 'pointer',
  fontFamily: 'var(--font-body)', fontSize: 13, fontWeight: 600,
};

const pillStyle: React.CSSProperties = {
  display: 'inline-flex', alignItems: 'center',
  padding: '4px 10px', borderRadius: 999,
  background: '#FFFFFF', color: '#1A1A1A',
  fontFamily: 'var(--font-mono)', fontSize: 10, fontWeight: 700,
  letterSpacing: '0.06em', textTransform: 'uppercase',
  border: '1px solid #E5E7EB',
};

/* Spinner, ListPanel → ./diagnostic/ (P1-CR-3 step 2). */
/* topicRu, levelRu → lib/diagnostic/utils.ts (P1-CR-3 step 1). */
