'use client';

import { useEffect, useMemo, useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { modules } from '@/lib/curriculum';
import { useAppStore } from '@/lib/store';

interface Turn {
  question: string;
  options: string[];
  correctIndex: number;
  selectedIndex: number;
  topic: string;
  explanation?: string;
}

interface ServerQuestion {
  question: string;
  options: string[];
  correctIndex: number;
  topic: string;
  explanation: string;
  index: number;
  total: number;
}

interface FinalResult {
  profession: string;
  professionRationale: string;
  level: 'basic' | 'intermediate' | 'advanced';
  strengths: string[];
  weaknesses: string[];
  recommendedModuleIds: number[];
  studyPlan: string;
}

type Phase = 'loading' | 'asking' | 'reviewing' | 'finalizing' | 'done' | 'error';

/**
 * Adaptive diagnostic test. Each question is generated by Gemini based on
 * the user's previous answers. After 15 questions the AI produces a
 * personalised profession + module recommendation.
 *
 * Flow:
 *   loading → asking → (user picks) → reviewing → next →
 *   ... 15 turns ... → finalizing → done
 */
export default function DiagnosticTest({ onClose }: { onClose: () => void }) {
  const openCourse = useAppStore((s) => s.openCourse);
  const [phase, setPhase] = useState<Phase>('loading');
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [history, setHistory] = useState<Turn[]>([]);
  const [current, setCurrent] = useState<ServerQuestion | null>(null);
  const [picked, setPicked] = useState<number | null>(null);
  const [final, setFinal] = useState<FinalResult | null>(null);

  /** Compact module summaries for the finalize prompt (id + title + desc). */
  const moduleSummaries = useMemo(() => {
    return modules.map((m) => ({
      id: m.id,
      sectionId: m.sectionId,
      title: m.title,
      description: m.description ?? '',
    }));
  }, []);

  const fetchNext = useCallback(async (h: Turn[]) => {
    setPhase('loading');
    setErrorMsg(null);
    try {
      const r = await fetch('/api/diagnostic', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ action: 'next', history: h }),
      });
      const json = await r.json();
      if (!r.ok || !json.ok) {
        const code = json?.error || `http-${r.status}`;
        const friendly =
          code === 'gemini-not-configured'
            ? 'AI-сервис временно недоступен. Попробуйте позже.'
            : `Не удалось получить следующий вопрос (${code}). Попробуйте ещё раз.`;
        console.error('[diagnostic] /next failed:', code, json);
        setErrorMsg(friendly);
        setPhase('error');
        return;
      }
      setCurrent(json as ServerQuestion);
      setPicked(null);
      setPhase('asking');
    } catch (err) {
      console.error('[diagnostic] /next threw:', err);
      setErrorMsg('Нет связи с сервером. Проверьте интернет.');
      setPhase('error');
    }
  }, []);

  const finalize = useCallback(async (h: Turn[]) => {
    setPhase('finalizing');
    setErrorMsg(null);
    try {
      const r = await fetch('/api/diagnostic', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ action: 'finalize', history: h, modules: moduleSummaries }),
      });
      const json = await r.json();
      if (!r.ok || !json.ok) {
        setErrorMsg('Не удалось получить рекомендацию. Попробуйте перезапустить тест.');
        setPhase('error');
        return;
      }
      setFinal(json as FinalResult);
      setPhase('done');
    } catch {
      setErrorMsg('Нет связи с сервером. Проверьте интернет.');
      setPhase('error');
    }
  }, [moduleSummaries]);

  // Kick off the first question on mount
  useEffect(() => {
    fetchNext([]);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handlePick = (idx: number) => {
    if (phase !== 'asking' || !current) return;
    setPicked(idx);
    setPhase('reviewing');
  };

  const handleNext = () => {
    if (!current || picked == null) return;
    const turn: Turn = {
      question: current.question,
      options: current.options,
      correctIndex: current.correctIndex,
      selectedIndex: picked,
      topic: current.topic,
      explanation: current.explanation,
    };
    const newHistory = [...history, turn];
    setHistory(newHistory);
    if (newHistory.length >= current.total) {
      finalize(newHistory);
    } else {
      fetchNext(newHistory);
    }
  };

  const restart = () => {
    setHistory([]);
    setCurrent(null);
    setPicked(null);
    setFinal(null);
    fetchNext([]);
  };

  const total = current?.total ?? 15;
  const indexNow = current?.index ?? history.length;
  const progressPct = Math.round((indexNow / total) * 100);
  const correctSoFar = history.filter((t) => t.selectedIndex === t.correctIndex).length;

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25, ease: [0.05, 0.7, 0.1, 1] }}
      style={{ maxWidth: 760, margin: '0 auto', padding: '0 var(--space-4)' }}
    >
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 18 }}>
        <button
          onClick={onClose}
          aria-label="Закрыть"
          style={{
            width: 36, height: 36, borderRadius: 10,
            background: '#F5F6F8', color: '#1A1A1A', border: 'none',
            cursor: 'pointer',
            display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
            transition: 'background 150ms',
          }}
          onMouseEnter={(e) => { e.currentTarget.style.background = '#E8E9ED'; }}
          onMouseLeave={(e) => { e.currentTarget.style.background = '#F5F6F8'; }}
        >
          <svg width={16} height={16} viewBox="0 0 24 24" fill="none"
            stroke="currentColor" strokeWidth={2.2} strokeLinecap="round" strokeLinejoin="round">
            <line x1="19" y1="12" x2="5" y2="12" />
            <polyline points="12 19 5 12 12 5" />
          </svg>
        </button>
        <div style={{ flex: 1 }}>
          <p style={{
            margin: 0,
            fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 600,
            color: '#9CA3AF', textTransform: 'uppercase', letterSpacing: '0.08em',
          }}>
            Диагностика
          </p>
          <h2 style={{
            margin: '2px 0 0',
            fontFamily: 'var(--font-display)', fontSize: 22, fontWeight: 700,
            color: '#1A1A1A', letterSpacing: '-0.02em', lineHeight: 1.2,
          }}>
            Адаптивный тест уровня знаний
          </h2>
        </div>
      </div>

      {/* Progress bar */}
      {phase !== 'done' && phase !== 'error' && (
        <div style={{ marginBottom: 22 }}>
          <div style={{
            display: 'flex', justifyContent: 'space-between', alignItems: 'baseline',
            marginBottom: 6,
          }}>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: '#6B7280' }}>
              {phase === 'finalizing'
                ? 'AI собирает рекомендацию…'
                : `Вопрос ${Math.min(indexNow + 1, total)} из ${total}`}
            </span>
            <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11, color: '#9CA3AF' }}>
              {correctSoFar}/{history.length} верных
            </span>
          </div>
          <div style={{
            height: 6, borderRadius: 999, background: '#F1F3F6', overflow: 'hidden',
          }}>
            <motion.div
              animate={{ width: `${progressPct}%` }}
              transition={{ duration: 0.4, ease: [0.05, 0.7, 0.1, 1] }}
              style={{ height: '100%', background: '#3B82F6', borderRadius: 999 }}
            />
          </div>
        </div>
      )}

      {/* Body */}
      <AnimatePresence mode="wait">
        {phase === 'loading' && (
          <motion.div key="loading" {...fadeProps} style={panelStyle}>
            <Spinner />
            <p style={loadingTextStyle}>AI готовит следующий вопрос…</p>
          </motion.div>
        )}

        {phase === 'finalizing' && (
          <motion.div key="finalizing" {...fadeProps} style={panelStyle}>
            <Spinner />
            <p style={loadingTextStyle}>Анализируем ответы и собираем рекомендацию…</p>
          </motion.div>
        )}

        {phase === 'error' && (
          <motion.div key="error" {...fadeProps} style={{
            ...panelStyle, background: '#FEF2F2', border: '1px solid #FCA5A5',
          }}>
            <p style={{
              fontFamily: 'var(--font-body)', fontSize: 14, fontWeight: 600,
              color: '#991B1B', marginBottom: 6,
            }}>
              Что-то пошло не так
            </p>
            <p style={{
              fontFamily: 'var(--font-body)', fontSize: 13, color: '#991B1B',
              lineHeight: 1.5, marginBottom: 14,
            }}>
              {errorMsg ?? 'Неизвестная ошибка.'}
            </p>
            <div style={{ display: 'flex', gap: 8 }}>
              <button onClick={() => fetchNext(history)} style={primaryBtn}>
                Попробовать снова
              </button>
              <button onClick={onClose} style={secondaryBtn}>Закрыть</button>
            </div>
          </motion.div>
        )}

        {(phase === 'asking' || phase === 'reviewing') && current && (
          <motion.div key={`q-${indexNow}`} {...fadeProps} style={panelStyle}>
            <p style={{
              fontFamily: 'var(--font-mono)', fontSize: 10, fontWeight: 700,
              color: '#9CA3AF', textTransform: 'uppercase', letterSpacing: '0.08em',
              margin: '0 0 8px',
            }}>
              Тема · {topicRu(current.topic)}
            </p>
            <h3 style={{
              fontFamily: 'var(--font-display)', fontSize: 18, fontWeight: 700,
              color: '#1A1A1A', letterSpacing: '-0.01em', lineHeight: 1.35,
              margin: '0 0 18px',
            }}>
              {current.question}
            </h3>
            <ul style={{ margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 10 }}>
              {current.options.map((opt, i) => {
                const isPicked = picked === i;
                const isReview = phase === 'reviewing';
                const isCorrect = i === current.correctIndex;
                let bg = '#F5F6F8';
                let border = 'none';
                let color = '#1A1A1A';
                if (isReview) {
                  if (isCorrect) { bg = '#ECFDF5'; border = '1px solid #A7F3D0'; color = '#065F46'; }
                  else if (isPicked) { bg = '#FEF2F2'; border = '1px solid #FCA5A5'; color = '#991B1B'; }
                } else if (isPicked) {
                  bg = '#EFF6FF'; border = '1px solid #BFDBFE'; color = '#1E40AF';
                }
                return (
                  <li key={i}>
                    <button
                      onClick={() => handlePick(i)}
                      disabled={isReview}
                      style={{
                        width: '100%', textAlign: 'left',
                        padding: '12px 16px', borderRadius: 12,
                        background: bg, border, color,
                        cursor: isReview ? 'default' : 'pointer',
                        fontFamily: 'var(--font-body)', fontSize: 14, lineHeight: 1.45,
                        display: 'flex', alignItems: 'flex-start', gap: 12,
                        transition: 'background 160ms, border-color 160ms, color 160ms',
                      }}
                      onMouseEnter={(e) => {
                        if (!isReview && !isPicked) e.currentTarget.style.background = '#E8E9ED';
                      }}
                      onMouseLeave={(e) => {
                        if (!isReview && !isPicked) e.currentTarget.style.background = '#F5F6F8';
                      }}
                    >
                      <span style={{
                        flexShrink: 0, marginTop: 2,
                        width: 22, height: 22, borderRadius: 6,
                        background: isReview && isCorrect ? '#10B981'
                          : isReview && isPicked ? '#DC2626'
                          : isPicked ? '#3B82F6'
                          : '#E2E4EA',
                        color: '#FFFFFF',
                        fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 700,
                        display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                      }}>
                        {String.fromCharCode(65 + i)}
                      </span>
                      <span style={{ flex: 1 }}>{opt}</span>
                    </button>
                  </li>
                );
              })}
            </ul>

            {phase === 'reviewing' && current.explanation && (
              <div style={{
                marginTop: 16, padding: '12px 14px',
                background: '#F8FAFC', borderRadius: 10,
                fontFamily: 'var(--font-body)', fontSize: 13, color: '#475569',
                lineHeight: 1.55,
              }}>
                <strong style={{ color: '#1A1A1A', display: 'block', marginBottom: 4 }}>Пояснение</strong>
                {current.explanation}
              </div>
            )}

            {phase === 'reviewing' && (
              <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 18 }}>
                <button onClick={handleNext} style={primaryBtn}>
                  {history.length + 1 >= total ? 'Получить рекомендацию' : 'Следующий вопрос →'}
                </button>
              </div>
            )}
          </motion.div>
        )}

        {phase === 'done' && final && (
          <motion.div key="done" {...fadeProps} style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
            {/* Hero card with profession */}
            <div style={{
              padding: 'clamp(20px, 4vw, 32px)',
              background: 'linear-gradient(135deg, #EFF6FF 0%, #F8FAFC 100%)',
              border: '1px solid #BFDBFE',
              borderRadius: 18,
            }}>
              <p style={{
                margin: 0,
                fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 700,
                color: '#1E40AF', textTransform: 'uppercase', letterSpacing: '0.08em',
              }}>
                Рекомендуемое направление
              </p>
              <h3 style={{
                margin: '8px 0 10px',
                fontFamily: 'var(--font-display)', fontSize: 28, fontWeight: 700,
                color: '#1A1A1A', letterSpacing: '-0.02em', lineHeight: 1.1,
              }}>
                {final.profession}
              </h3>
              <p style={{
                margin: 0,
                fontFamily: 'var(--font-body)', fontSize: 14, color: '#374151',
                lineHeight: 1.55,
              }}>
                {final.professionRationale}
              </p>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, marginTop: 14 }}>
                <span style={pillStyle}>Уровень: {levelRu(final.level)}</span>
                <span style={pillStyle}>{correctSoFar}/{history.length} верных ответов</span>
              </div>
            </div>

            {/* Strengths + weaknesses */}
            {(final.strengths.length > 0 || final.weaknesses.length > 0) && (
              <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
                gap: 14,
              }}>
                {final.strengths.length > 0 && (
                  <ListPanel title="Сильные стороны" tone="green" items={final.strengths} />
                )}
                {final.weaknesses.length > 0 && (
                  <ListPanel title="Над чем поработать" tone="amber" items={final.weaknesses} />
                )}
              </div>
            )}

            {/* Study plan */}
            {final.studyPlan && (
              <div style={{
                padding: '16px 18px', borderRadius: 14,
                background: '#FFFFFF', border: '1px solid #E5E7EB',
              }}>
                <p style={{
                  margin: 0,
                  fontFamily: 'var(--font-mono)', fontSize: 10, fontWeight: 700,
                  color: '#6B7280', textTransform: 'uppercase', letterSpacing: '0.08em',
                }}>
                  План обучения
                </p>
                <p style={{
                  margin: '6px 0 0',
                  fontFamily: 'var(--font-body)', fontSize: 14, color: '#1A1A1A',
                  lineHeight: 1.55,
                }}>
                  {final.studyPlan}
                </p>
              </div>
            )}

            {/* Recommended modules */}
            {final.recommendedModuleIds.length > 0 && (
              <div>
                <h4 style={{
                  margin: '0 0 12px',
                  fontFamily: 'var(--font-display)', fontSize: 16, fontWeight: 700,
                  color: '#1A1A1A',
                }}>
                  Рекомендуемые модули
                </h4>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                  {final.recommendedModuleIds.map((id, idx) => {
                    const mod = modules.find((m) => m.id === id);
                    if (!mod) return null;
                    return (
                      <button
                        key={id}
                        onClick={() => {
                          // Open the module - if it has courses, jump to the first one
                          if (mod.courses[0]) openCourse(mod.courses[0].id);
                        }}
                        style={{
                          textAlign: 'left',
                          display: 'flex', alignItems: 'center', gap: 14,
                          padding: '14px 16px',
                          background: '#FFFFFF', border: '1px solid #E5E7EB',
                          borderRadius: 12, cursor: 'pointer',
                          transition: 'background 150ms, border-color 150ms, transform 150ms',
                        }}
                        onMouseEnter={(e) => {
                          e.currentTarget.style.background = '#F8FAFC';
                          e.currentTarget.style.borderColor = '#CBD5E1';
                        }}
                        onMouseLeave={(e) => {
                          e.currentTarget.style.background = '#FFFFFF';
                          e.currentTarget.style.borderColor = '#E5E7EB';
                        }}
                      >
                        <span style={{
                          width: 32, height: 32, borderRadius: 10,
                          background: '#EFF6FF', color: '#1E40AF',
                          display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
                          fontFamily: 'var(--font-mono)', fontSize: 12, fontWeight: 700,
                          flexShrink: 0,
                        }}>
                          {idx + 1}
                        </span>
                        <span style={{ flex: 1, minWidth: 0 }}>
                          <span style={{
                            display: 'block',
                            fontFamily: 'var(--font-body)', fontSize: 14, fontWeight: 600,
                            color: '#1A1A1A', lineHeight: 1.3,
                          }}>
                            {mod.title}
                          </span>
                          <span style={{
                            display: 'block', marginTop: 2,
                            fontFamily: 'var(--font-body)', fontSize: 12, color: '#6B7280',
                            lineHeight: 1.4,
                          }}>
                            {mod.description}
                          </span>
                        </span>
                        <svg width={14} height={14} viewBox="0 0 24 24" fill="none"
                          stroke="#9CA3AF" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round"
                          style={{ flexShrink: 0 }}>
                          <line x1="5" y1="12" x2="19" y2="12" />
                          <polyline points="12 5 19 12 12 19" />
                        </svg>
                      </button>
                    );
                  })}
                </div>
              </div>
            )}

            {/* Footer actions */}
            <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 6 }}>
              <button onClick={restart} style={secondaryBtn}>Пройти заново</button>
              <button onClick={onClose} style={primaryBtn}>Закрыть</button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

/* ───── helpers ───── */

const fadeProps = {
  initial: { opacity: 0, y: 8 },
  animate: { opacity: 1, y: 0 },
  exit: { opacity: 0, y: -6 },
  transition: { duration: 0.25, ease: [0.05, 0.7, 0.1, 1] as const },
};

const panelStyle = {
  background: '#FFFFFF',
  border: '1px solid #F0F1F5',
  borderRadius: 18,
  padding: 'clamp(20px, 4vw, 28px)',
};

const loadingTextStyle = {
  marginTop: 12,
  fontFamily: 'var(--font-body)',
  fontSize: 13,
  color: '#6B7280',
  textAlign: 'center' as const,
};

const primaryBtn: React.CSSProperties = {
  padding: '10px 20px', borderRadius: 10,
  background: '#3B82F6', color: '#FFFFFF',
  border: 'none', cursor: 'pointer',
  fontFamily: 'var(--font-body)', fontSize: 13, fontWeight: 600,
  transition: 'background 180ms',
};

const secondaryBtn: React.CSSProperties = {
  padding: '10px 16px', borderRadius: 10,
  background: 'transparent', color: '#6B7280',
  border: 'none', cursor: 'pointer',
  fontFamily: 'var(--font-body)', fontSize: 13, fontWeight: 600,
};

const pillStyle: React.CSSProperties = {
  display: 'inline-flex', alignItems: 'center',
  padding: '4px 10px', borderRadius: 999,
  background: '#FFFFFF', color: '#1E40AF',
  fontFamily: 'var(--font-mono)', fontSize: 10, fontWeight: 700,
  letterSpacing: '0.06em', textTransform: 'uppercase',
  border: '1px solid #BFDBFE',
};

function Spinner() {
  return (
    <div style={{
      width: 36, height: 36, margin: '0 auto',
      border: '3px solid #E2E4EA', borderTopColor: '#3B82F6',
      borderRadius: '50%',
      animation: 'diagnostic-spin 0.9s linear infinite',
    }}>
      <style jsx global>{`
        @keyframes diagnostic-spin { to { transform: rotate(360deg); } }
      `}</style>
    </div>
  );
}

function ListPanel({ title, tone, items }: {
  title: string; tone: 'green' | 'amber'; items: string[];
}) {
  const palette = tone === 'green'
    ? { bg: '#ECFDF5', border: '#A7F3D0', label: '#065F46', dot: '#10B981' }
    : { bg: '#FFFBEB', border: '#FCD34D', label: '#92400E', dot: '#F59E0B' };
  return (
    <div style={{
      padding: '14px 16px',
      background: palette.bg, border: `1px solid ${palette.border}`,
      borderRadius: 14,
    }}>
      <p style={{
        margin: '0 0 10px',
        fontFamily: 'var(--font-mono)', fontSize: 10, fontWeight: 700,
        color: palette.label, textTransform: 'uppercase', letterSpacing: '0.08em',
      }}>
        {title}
      </p>
      <ul style={{ margin: 0, padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 6 }}>
        {items.map((s, i) => (
          <li key={i} style={{
            display: 'flex', alignItems: 'flex-start', gap: 8,
            fontFamily: 'var(--font-body)', fontSize: 13, color: '#1A1A1A',
            lineHeight: 1.45,
          }}>
            <span style={{
              flexShrink: 0, marginTop: 6,
              width: 6, height: 6, borderRadius: '50%', background: palette.dot,
            }} />
            <span>{s}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

function topicRu(topic: string): string {
  const map: Record<string, string> = {
    anatomy: 'анатомия',
    physiology: 'физиология',
    biochemistry: 'биохимия',
    pharmacology: 'фармакология',
    pathology: 'патология',
    'internal-medicine': 'внутренние болезни',
    surgery: 'хирургия',
    pediatrics: 'педиатрия',
    obstetrics: 'акушерство',
    emergency: 'неотложка',
    'public-health': 'общественное здоровье',
    ethics: 'этика',
    'clinical-skills': 'клинические навыки',
    'lab-diagnostics': 'лабораторная диагностика',
    imaging: 'визуализация',
  };
  return map[topic] ?? topic;
}

function levelRu(level: 'basic' | 'intermediate' | 'advanced'): string {
  return level === 'basic' ? 'базовый'
    : level === 'advanced' ? 'продвинутый'
    : 'средний';
}
