'use client';

import { useEffect, useMemo, useState, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { modules } from '@/lib/curriculum';
import { useAppStore } from '@/lib/store';
import { log } from '@/lib/log';
import type {
  Turn,
  ServerQuestion,
  FinalResult,
  Phase,
} from '@/lib/diagnostic/types';
import { friendlyError } from '@/lib/diagnostic/utils';
import { DiagnosticHeader } from './diagnostic/DiagnosticHeader';
import { DiagnosticProgress } from './diagnostic/DiagnosticProgress';
import { LoadingPanel } from './diagnostic/LoadingPanel';
import { FinalizingPanel } from './diagnostic/FinalizingPanel';
import { ErrorPanel } from './diagnostic/ErrorPanel';
import { QuestionPanel } from './diagnostic/QuestionPanel';
import { DonePanel } from './diagnostic/DonePanel';

/**
 * Adaptive diagnostic test. Each question is generated by Gemini based on
 * the user's previous answers. After 15 questions the AI produces a
 * personalised profession + module recommendation.
 *
 * Flow:
 *   loading → asking → (user picks) → reviewing → next →
 *   ... 15 turns ... → finalizing → done
 */
export default function DiagnosticTest({ onClose }: { onClose: () => void }) {
  const openCourse = useAppStore((s) => s.openCourse);
  const setLastDiagnosticResult = useAppStore((s) => s.setLastDiagnosticResult);
  const cachedResult = useAppStore((s) => s.lastDiagnosticResult);
  // Если у пользователя есть сохранённый результат — стартуем сразу с
  // экрана 'done'. Это даёт возможность вернуться к рекомендациям без
  // повторного прохождения 30 вопросов. Кнопка «Пройти заново»
  // обнуляет кеш и начинает с loading.
  const [phase, setPhase] = useState<Phase>(cachedResult ? 'done' : 'loading');
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  // P1-PERF-NEW-5 — streaming preview text (Gemini partial output) для
  // показа пользователю под spinner'ом в "finalizing" phase. Обновляется
  // по мере прихода chunks от /api/diagnostic NDJSON stream.
  const [streamingPreview, setStreamingPreview] = useState<string>('');
  const [history, setHistory] = useState<Turn[]>([]);
  const [current, setCurrent] = useState<ServerQuestion | null>(null);
  const [picked, setPicked] = useState<number | null>(null);
  const [final, setFinal] = useState<FinalResult | null>(
    cachedResult
      ? {
          profession: cachedResult.profession,
          professionRationale: cachedResult.professionRationale,
          level: cachedResult.level,
          strengths: cachedResult.strengths,
          weaknesses: cachedResult.weaknesses,
          recommendedModuleIds: cachedResult.recommendedModuleIds,
          studyPlan: cachedResult.studyPlan,
        }
      : null,
  );

  /** Compact module summaries for the finalize prompt (id + title + desc). */
  const moduleSummaries = useMemo(() => {
    return modules.map((m) => ({
      id: m.id,
      sectionId: m.sectionId,
      title: m.title,
      description: m.description ?? '',
    }));
  }, []);

  const fetchNext = useCallback(async (h: Turn[]) => {
    setPhase('loading');
    setErrorMsg(null);

    // One automatic retry-with-backoff on transient errors. The diagnostic
    // depends on a chain of API calls; a single 429 from Google's free
    // quota during a rolling wave of users would otherwise force the user
    // to manually click "Попробовать снова" repeatedly. We do exactly one
    // silent retry after a 2.5s wait so the user never sees the toast for
    // brief upstream blips.
    let attempt = 0;
    while (attempt < 2) {
      try {
        const r = await fetch('/api/diagnostic', {
          method: 'POST',
          headers: { 'content-type': 'application/json' },
          body: JSON.stringify({ action: 'next', history: h }),
        });
        const json = await r.json();
        if (r.ok && json.ok) {
          setCurrent(json as ServerQuestion);
          setPicked(null);
          setPhase('asking');
          return;
        }
        const code = json?.error || `http-${r.status}`;
        const f = friendlyError(code);
        if (attempt === 0 && f.retryable) {
          attempt++;
          await new Promise((res) => setTimeout(res, 2500));
          continue;
        }
        // P2-NEW-12 — структурный лог через lib/log с redaction.
        log.error({ event: 'diagnostic_next_failed', code });
        setErrorMsg(f.msg);
        setPhase('error');
        return;
      } catch (err) {
        if (attempt === 0) {
          attempt++;
          await new Promise((res) => setTimeout(res, 2500));
          continue;
        }
        log.error({
          event: 'diagnostic_next_threw',
          message: (err as Error)?.message ?? String(err).slice(0, 200),
        });
        setErrorMsg('Нет связи с сервером. Проверьте интернет.');
        setPhase('error');
        return;
      }
    }
  }, []);

  const finalize = useCallback(async (h: Turn[]) => {
    setPhase('finalizing');
    setErrorMsg(null);
    setStreamingPreview(''); // P1-PERF-NEW-5 — reset preview on each attempt
    // Same one-shot retry pattern as fetchNext — finalize is a single
    // expensive call that summarises all 30 turns; we'd rather wait 2.5s
    // and retry than burn the whole completed test on a transient 429.
    let attempt = 0;
    while (attempt < 2) {
      try {
        // P1-PERF-NEW-5 — request streaming response. Server returns
        // application/x-ndjson с строками { type: 'chunk' | 'done', ... }.
        // Каждый 'chunk' даёт accumulated raw text от Gemini, чтобы UI
        // мог показать live preview ("анализирую...") вместо blank
        // spinner на 3-8 секунд. На любую ошибку streaming server emit'ит
        // 'done' с rule-based fallback — UX никогда не падает.
        const r = await fetch('/api/diagnostic', {
          method: 'POST',
          headers: {
            'content-type': 'application/json',
            'accept': 'application/x-ndjson',
          },
          body: JSON.stringify({ action: 'finalize', history: h, modules: moduleSummaries }),
        });

        // Streaming path: read NDJSON line by line.
        if (r.ok && r.body && r.headers.get('content-type')?.includes('application/x-ndjson')) {
          const reader = r.body.pipeThrough(new TextDecoderStream()).getReader();
          let buf = '';
          let finalResult: FinalResult | null = null;
          try {
            for (;;) {
              const { done, value } = await reader.read();
              if (done) break;
              buf += value;
              let idx;
              while ((idx = buf.indexOf('\n')) >= 0) {
                const line = buf.slice(0, idx).trim();
                buf = buf.slice(idx + 1);
                if (!line) continue;
                try {
                  const evt = JSON.parse(line) as { type: string; text?: string; result?: FinalResult };
                  if (evt.type === 'chunk' && typeof evt.text === 'string') {
                    setStreamingPreview(evt.text);
                  } else if (evt.type === 'done' && evt.result) {
                    finalResult = evt.result;
                  }
                } catch { /* skip malformed line */ }
              }
            }
          } finally {
            reader.cancel().catch(() => { /* already closed */ });
          }
          if (finalResult) {
            setFinal(finalResult);
            setPhase('done');
            setLastDiagnosticResult({
              ...finalResult,
              correct: h.filter((t) => t.selectedIndex === t.correctIndex).length,
              total: h.length,
              completedAt: new Date().toISOString(),
            });
            return;
          }
          // Stream ended without 'done' event — treat as transient
          throw new Error('stream-ended-without-result');
        }

        // Fallback: non-streaming JSON response (server didn't honor ndjson Accept)
        const json = await r.json();
        if (r.ok && json.ok) {
          const result = json as FinalResult;
          setFinal(result);
          setPhase('done');
          // Persist в стор: пользователь может закрыть и вернуться,
          // или открыть на другом устройстве (через Supabase-sync).
          // correctSoFar/history.length считаются ниже в render —
          // здесь читаем актуальные значения из state через get().
          setLastDiagnosticResult({
            ...result,
            correct: h.filter((t) => t.selectedIndex === t.correctIndex).length,
            total: h.length,
            completedAt: new Date().toISOString(),
          });
          return;
        }
        const code = json?.error || `http-${r.status}`;
        const f = friendlyError(code);
        if (attempt === 0 && f.retryable) {
          attempt++;
          await new Promise((res) => setTimeout(res, 2500));
          continue;
        }
        setErrorMsg(f.msg);
        setPhase('error');
        return;
      } catch {
        if (attempt === 0) {
          attempt++;
          await new Promise((res) => setTimeout(res, 2500));
          continue;
        }
        setErrorMsg('Нет связи с сервером. Проверьте интернет.');
        setPhase('error');
        return;
      }
    }
  }, [moduleSummaries]);

  // Kick off the first question on mount, но только если нет
  // cached-результата. С cached — сразу показываем 'done' (см. setPhase
  // в useState инициализаторе выше) и не дёргаем API.
  useEffect(() => {
    if (cachedResult) return;
    fetchNext([]);
    // eslint-disable-next-line react-hooks/exhaustive-deps -- run-once on mount. fetchNext is a stable closure defined in the same render scope; re-firing on its identity change would queue duplicate API calls during state transitions.
  }, []);

  const handlePick = (idx: number) => {
    if (phase !== 'asking' || !current) return;
    setPicked(idx);
    setPhase('reviewing');
  };

  const handleNext = () => {
    if (phase !== 'reviewing' || !current || picked == null) return;
    const turn: Turn = {
      question: current.question,
      options: current.options,
      correctIndex: current.correctIndex,
      selectedIndex: picked,
      topic: current.topic,
      explanation: current.explanation,
    };
    const newHistory = [...history, turn];
    setHistory(newHistory);
    if (newHistory.length >= current.total) {
      finalize(newHistory);
    } else {
      fetchNext(newHistory);
    }
  };

  const restart = () => {
    setHistory([]);
    setCurrent(null);
    setPicked(null);
    setFinal(null);
    // Очищаем сохранённый результат — пользователь явно сказал
    // «Пройти заново», старые рекомендации больше не актуальны.
    setLastDiagnosticResult(null);
    setPhase('loading');
    fetchNext([]);
  };

  const total = current?.total ?? 30;
  const indexNow = current?.index ?? history.length;
  const progressPct = Math.round((indexNow / total) * 100);
  const correctSoFar = history.filter((t) => t.selectedIndex === t.correctIndex).length;

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25, ease: [0.05, 0.7, 0.1, 1] }}
      className="max-w-[760px] mx-auto px-4"
    >
      <DiagnosticHeader onClose={onClose} />
      <DiagnosticProgress
        phase={phase}
        indexNow={indexNow}
        total={total}
        correctSoFar={correctSoFar}
        historyLength={history.length}
        progressPct={progressPct}
      />

      {/* Body */}
      <AnimatePresence mode="wait">
        {phase === 'loading' && <LoadingPanel />}
        {phase === 'finalizing' && <FinalizingPanel streamingPreview={streamingPreview} />}
        {phase === 'error' && (
          <ErrorPanel
            errorMsg={errorMsg}
            onRetry={() => fetchNext(history)}
            onClose={onClose}
          />
        )}

        {(phase === 'asking' || phase === 'reviewing') && current && (
          <QuestionPanel
            current={current}
            phase={phase}
            picked={picked}
            indexNow={indexNow}
            historyLength={history.length}
            total={total}
            onPick={handlePick}
            onNext={handleNext}
          />
        )}

        {phase === 'done' && final && (
          <DonePanel
            final={final}
            correctSoFar={correctSoFar}
            historyLength={history.length}
            onOpenCourse={openCourse}
            onRestart={restart}
            onClose={onClose}
          />
        )}
      </AnimatePresence>
    </motion.div>
  );
}

/* Spinner, ListPanel, panels → ./diagnostic/ (P1-CR-3 steps 2-4). */
/* topicRu, levelRu → lib/diagnostic/utils.ts (P1-CR-3 step 1). */
/* Inline style consts → ./diagnostic/styles.ts (P1-CR-3 step 4). */
